/**
 * AUTOGENERATED Prisma CLI Configuration - Appointment Service
 *
 * This config is used by Prisma CLI commands (generate, migrate, db push).
 */
export default {
  schema: 'prisma/schema.prisma',
  datasource: {
    url: process.env.DATABASE_URL,
  },
};
