#!/usr/bin/env bash
# Run a native backend that enables the `prisma` feature and lists `postgres` in `dependsOn` through a real `tdk up` (#531):
# the service must start after TDK's Postgres, apply its migrations, and persist an order written through Prisma Client, which
# this script then reads back from Postgres itself.
#
# Needs Docker, Tilt, bun and a built CLI (cli/dist). Uses an isolated throwaway project with a unique name and random alternate
# ports, and removes only the containers, networks and images carrying its own name (it never calls `tdk down`, which can touch
# other projects' containers).
#
# Usage: scripts/e2e/prisma-postgres.sh
#   VERIFY_WAIT_SECONDS   how long to wait for the first start (default 900)
set -euo pipefail

root="$(cd "$(dirname "$0")/../.." && pwd)"
fixture="$root/tests/e2e/fixtures/native-prisma-postgres"
proj="prisma$$"
work="$(mktemp -d)/$proj"
mkdir -p "$work"
http_port=$((30000 + RANDOM % 2000))
tilt_port=$((10400 + RANDOM % 500))
# Vendor and run this checkout's engine, not a published one (the backgrounded `tdk up` needs it too).
export TDK_EXTENSION_SOURCE="$root"
tdk() { node "$root/cli/bin/tdk.js" "$@"; }

cleanup() {
  # Anchored on the whole project name: prisma123 must not match a concurrent run's prisma1234.
  pkill -f "tilt up.*/${proj}/" >/dev/null 2>&1 || true
  docker rm -f $(docker ps -aq --filter "name=^${proj}[-_]") >/dev/null 2>&1 || true
  docker network ls --format '{{.Name}}' | grep -E "^${proj}_" | xargs -r docker network rm >/dev/null 2>&1 || true
  docker images --format '{{.Repository}}:{{.Tag}}' | grep -E "^(app_${proj}:|${proj}-l[0-9]+)" | xargs -r docker rmi -f >/dev/null 2>&1 || true
}
trap cleanup EXIT

cd "$work"
git init -q .
tdk project --yes >/dev/null 2>&1
printf '\nTDK_HTTP_PORT=%s\nTDK_HTTPS_PORT=%s\nTDK_POSTGRES_PORT=%s\n' \
  "$http_port" "$((32000 + RANDOM % 2000))" "$((34000 + RANDOM % 2000))" >> .env

tdk resource orders-api --type backend --stack "$proj" --yes >/dev/null
svc="services/$proj/orders-api"
cp -R "$fixture/src/." "$svc/src/"
cp -R "$fixture/prisma" "$svc/prisma"
python3 - "$svc" <<'PY'
import json, sys
svc = sys.argv[1]
manifest = json.load(open(f"{svc}/service.json"))
manifest["featuresEnabled"] = sorted(set(manifest.get("featuresEnabled", [])) | {"prisma"})
manifest["dependsOn"] = sorted(set(manifest.get("dependsOn", [])) | {"postgres"})
json.dump(manifest, open(f"{svc}/service.json", "w"), indent=2)
open(f"{svc}/service.json", "a").write("\n")
package = json.load(open(f"{svc}/package.json"))
package["dependencies"].update({"@prisma/client": "^7", "@prisma/adapter-pg": "^7", "pg": "^8"})
package.setdefault("devDependencies", {})["prisma"] = "^7"
json.dump(package, open(f"{svc}/package.json", "w"), indent=2)
open(f"{svc}/package.json", "a").write("\n")
PY
(cd "$svc" && bun install >/dev/null)
tdk config regenerate >/dev/null

# `tdk doctor` must accept what the engine will run. Other doctor findings (host ports, a missing container runtime) are not this test's
# business, so assert the two checks this change owns: both must be present and pass, and neither may be a warning.
tdk doctor --no-ping --json >"$work/doctor.json" 2>"$work/doctor.err" || true
python3 - "$work/doctor.json" <<'PY'
import json, sys
try:
    checks = json.load(open(sys.argv[1]))["data"]["checks"]
except Exception as error:
    sys.exit(f"FAIL: tdk doctor --json produced no readable report ({error})")
wanted = ("Prisma database", "dependsOn targets")
for name in wanted:
    found = [c for c in checks if c["name"] == name]
    if not found:
        sys.exit(f"FAIL: tdk doctor has no '{name}' check")
    check = found[0]
    if not check.get("didPass") or check.get("isWarning") or check.get("isSkipped"):
        sys.exit(f"FAIL: tdk doctor '{name}': {check.get('message')}")
print("tdk doctor: " + ", ".join(f"'{n}' passes" for n in wanted))
PY

started="$(date +%s)"
TILT_PORT="$tilt_port" nohup node "$root/cli/bin/tdk.js" up "$proj" >"$work/up.log" 2>&1 &

host="api.$proj.localhost"
base="http://127.0.0.1:$http_port/api/orders"
status=000
for _ in $(seq 1 "${VERIFY_WAIT_SECONDS:-900}"); do
  status="$(curl -s -o /dev/null -m 3 -w '%{http_code}' -H "Host: $host" "$base/health" || true)"
  [ "$status" = "200" ] && break
  sleep 1
done
if [ "$status" != "200" ]; then
  echo "FAIL: GET $base/health -> $status after ${VERIFY_WAIT_SECONDS:-900}s" >&2
  tail -40 "$work/up.log" >&2 || true
  docker logs "${proj}-autogenerated-orders-api-1" 2>&1 | tail -20 >&2 || true
  exit 1
fi
echo "first start: $(( $(date +%s) - started ))s from launching tdk up to the first 200 through Traefik"

item="prisma-postgres-e2e"
created="$(curl -fsS -m 10 -H "Host: $host" -H 'content-type: application/json' -d "{\"item\":\"$item\"}" "$base/orders")"
echo "POST /orders -> $created"

# Read it back from Postgres itself, not through the service that wrote it.
pw="$(grep -E '^DB_PASSWORD=' .env | head -1 | cut -d= -f2-)"
psql_in_container() { docker exec -e PGPASSWORD="$pw" "${proj}_postgres" psql -U "$proj" -tA "$@"; }
db="$(psql_in_container -d postgres -c "select datname from pg_database where datname like '${proj}%' limit 1")"
got="$(psql_in_container -d "$db" -c "select item from \"Order\" where item = '$item'")"
if [ "$got" = "$item" ]; then
  echo "PASS: orders-api (prisma feature, dependsOn postgres) migrated its schema and persisted '$item' in $db"
else
  echo "FAIL: expected '$item' in $db.\"Order\", got '$got'" >&2
  exit 1
fi
