appName: appointment-planner-frontend
appType: frontend
stack: appointment-planner
port: 3005
backendName: appointment-planner-backend
basePath: /appointment-planner
features:
replicas: 1
runtime: bun
