# =============================================================================
# 🧩 ORCHESTRATOR APPLY - COMPOSE RESOURCE REGISTRATION (Refactored)
# =============================================================================

# === INLINED CONSTANTS for pure extension loading ===
OUTPUT = struct(AUTOGENERATED_FOLDER = ".autogenerated")
# === END INLINED CONSTANTS ===


load('../../../platform/docker/index.star', 'Docker')
load('../../../platform/docker/constants.star', 'PlatformDockerConstants')

load('./builders/typescript.star', 'TypescriptBuilders')


def _build_infra_dependencies(service_name, should_enable, ctx, has_backend=False):
    infra_deps = []
    if should_enable('database-management'):
        infra_deps.append('postgres')
        if has_backend:
            infra_deps.append('provision-db-' + service_name)
    if should_enable(PlatformDockerConstants.VERDACCIO_SERVICE_NAME):
        infra_deps.append(PlatformDockerConstants.VERDACCIO_SERVICE_NAME)
    if should_enable('golden-image') and ctx.get('golden_image_resource'):
        infra_deps.append(ctx['golden_image_resource'])
    return infra_deps


def _resolve_dependency_to_resource(dep_name, all_services_map):
    """
    Resolve a short dependency name (e.g., 'identity') to the full YAML resource name.
    
    The discovery registry creates YAML resources with names like:
    - 'identity-management-backend-yaml' for identity backend
    - 'mdblaster-docs-yaml' for mdblaster docs
    
    But manifests reference them as short names like 'identity' or 'mdblaster'.
    """
    # Check if already a full YAML resource name
    if dep_name in all_services_map:
        return dep_name
    
    # Try with -yaml suffix (for resources already resolved)
    yaml_name = dep_name + '-yaml'
    if yaml_name in all_services_map:
        return yaml_name
    
    # Try to find matching service by domain/short name
    for service_name, service_info in all_services_map.items():
        # Check if this service's domain matches the dependency
        service_domain = service_info.get('domain', '')
        if service_domain == dep_name:
            # Return the first resource of this service with -yaml suffix
            resources = service_info.get('resources', [])
            if resources:
                # Prefer backend resources over frontends
                for res in resources:
                    if not res.get('frontend', False):
                        return res['name'] + '-yaml'
                # Fallback to first resource
                return resources[0]['name'] + '-yaml'
    
    # Try pattern matching: identity -> identity-*-yaml
    for service_name in all_services_map.keys():
        if service_name.startswith(dep_name + '-') and service_name.endswith('-yaml'):
            return service_name
    
    # Return original with -yaml suffix as last resort
    return dep_name + '-yaml'


def _build_resource_deps(res, res_name, manifest, service_config, infra_deps, config_gen_resources, resource_manifests, runtime_flags, all_services_map=None):
    res_deps = list(infra_deps)
    if res_name in config_gen_resources:
        res_deps.append(config_gen_resources[res_name])
    if res.get('frontend', False):
        backend_name = manifest.get('backendName', res_name.replace('frontend', 'backend'))
        if backend_name != res_name and backend_name in resource_manifests:
            res_deps.append(backend_name)
    elif runtime_flags['enforce_migrator_deps'] and service_config.get('has_migrator', False):
        migrator_name = service_config['name'] + '-db-migrator'
        if migrator_name not in res_deps:
            res_deps.append(migrator_name)
    
    # NEW: Resolve internalDependencies from manifest
    internal_deps = manifest.get('internalDependencies', [])
    for dep in internal_deps:
        resolved_dep = _resolve_dependency_to_resource(dep, all_services_map)
        if resolved_dep and resolved_dep not in res_deps:
            res_deps.append(resolved_dep)
    
    return res_deps


def _register_replicas(config, auto_init_apps):
    """Register additional replica resources for high-availability services."""
    replicas = config.get('replicas', 1)
    if replicas <= 1:
        return
    for i in range(2, replicas + 1):
        replica_name = config['res_name'] + '-' + str(i)
        dc_resource(
            replica_name,
            labels=config['labels'],
            resource_deps=config['res_deps'],
            auto_init=auto_init_apps,
        )


def _build_live_update_rules(res_path, full_res_path, syncs):
    """Build live update sync and run rules for a resource."""
    live_update_rules = []
    for sync_path in syncs:
        full_sync_path = full_res_path + '/' + sync_path
        dest = '/app/' + full_res_path + '/' + sync_path
        live_update_rules.append(sync(full_sync_path, dest))
    
    package_json_path = '/app/' + full_res_path + '/package.json'
    bun_lock_path = '/app/' + full_res_path + '/bun.lock'
    live_update_rules.append(run('cd /app/' + full_res_path + ' && bun install', 
                                 trigger=[package_json_path, bun_lock_path]))
    return live_update_rules


def _register_docker_build(config, live_update_rules):
    """Register docker_build with live_update for hot-reload support."""
    image_name = config['service_name'] + '_' + config['res_name'] + ':dev'
    # Use custom dockerfile from config if specified, otherwise use autogenerated default
    dockerfile = config.get('dockerfile', config['res_path'] + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/Dockerfile.app.autogenerated')
    print("DEBUG: Building " + config['res_name'] + " with dockerfile: " + dockerfile)
    TypescriptBuilders.build_typescript_service(
        image_name,
        '.',
        dockerfile,
        live_update_rules,
        config['res_deps'],
        env=config.get('env'),
    )


def _register_run_only_resource(config, service_path, compose_project_name):
    """Register a run-only local resource for docker compose up."""
    local_resource(
        name=config['res_name'] + '-run-only',
        cmd='docker compose -p '
            + compose_project_name
            + ' -f '
            + service_path
            + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/docker-compose.app.autogenerated.yml up -d --no-build '
            + config['res_name'],
        labels=config['labels'] + ['run-only'],
        resource_deps=config['res_deps'],
        auto_init=False,
        allow_parallel=True,
    )


def _register_single_resource(config, service_path, compose_project_name, auto_init_apps):
    """Register a single dc_resource with optional docker_build and run-only resource."""
    print("DEBUG _register_single_resource: " + config['res_name'] + " syncs: " + str(config.get('syncs')))
    app_type = config.get('app_type', 'backend')
    
    # Skip docker_build for libraries - they don't have Dockerfiles
    if app_type == 'library':
        print("DEBUG: Skipping docker_build for " + config['res_name'] + " (library type)")
    elif config.get('syncs'):
        print("DEBUG: Registering docker_build for " + config['res_name'])
        live_update_rules = _build_live_update_rules(
            config['res_path'],
            config['res_path'],
            config['syncs']
        )
        _register_docker_build(config, live_update_rules)
    else:
        print("DEBUG: Skipping docker_build for " + config['res_name'] + " (no syncs)")

    dc_resource(
        config['res_name'],
        labels=config['labels'],
        resource_deps=config['res_deps'],
        auto_init=auto_init_apps,
    )

    _register_run_only_resource(config, service_path, compose_project_name)
    _register_replicas(config, auto_init_apps)


def _register_dc_resources(resource_configs, service_path, compose_project_name, auto_init_apps):
    """Register all dc_resources for the service."""
    for config in resource_configs:
        _register_single_resource(config, service_path, compose_project_name, auto_init_apps)


def _has_backend_resource(service_config, resource_manifests):
    """Check if service has a backend resource."""
    for resource in service_config.get('resources', []):
        manifest = resource_manifests.get(resource['name'], {})
        if manifest.get('appType') == 'backend':
            return True
    return False


def _should_skip_frontend(res, should_enable):
    """Check if frontend resource should be skipped (backends-only mode)."""
    return res.get('frontend', False) and should_enable('backends-only')


def _process_frontend_resource(res, manifest, full_res_path, service_path, service_name, should_enable):
    """Process a frontend resource and return compose entry."""
    target_path = res.get('target_path', manifest.get('target_path', '/usr/share/nginx/html'))
    use_nginx = 'nginx' in target_path or target_path == '/usr/share/nginx/html'
    Docker.frontend(
        full_res_path,
        res['name'],
        target_path,
        use_nginx,
        use_golden=should_enable('golden-image'),
    )
    return Docker.frontend_compose(service_path, service_name, res, manifest)


def _process_backend_resource(res, manifest, full_res_path, service_path, service_name, should_enable):
    """Process a backend resource and return compose entry."""
    Docker.backend(
        full_res_path,
        res['name'],
        res.get('start_command'),
        use_golden=should_enable('golden-image'),
    )
    return Docker.backend_compose(service_path, service_name, res, manifest)


def _build_resource_config(res, manifest, service_config, full_res_path, infra_deps, 
                          config_gen_resources, resource_manifests, runtime_flags, all_services_map=None):
    """Build configuration dict for a single resource."""
    res_name = res['name']
    res_deps = _build_resource_deps(
        res, res_name, manifest, service_config, infra_deps,
        config_gen_resources, resource_manifests, runtime_flags, all_services_map,
    )
    replicas = manifest.get('replicas', 1)
    if runtime_flags['disable_app_replicas']:
        replicas = 1
    
    # Extract environment variables from manifest params
    env_vars = manifest.get('params', {})
    
    return {
        'res_name': res_name,
        'service_name': service_config['name'],
        'res_deps': res_deps,
        'labels': ['app.' + res_name],
        'replicas': replicas,
        'syncs': res.get('syncs', []),
        'app_type': manifest.get('appType', 'backend'),
        'dockerfile': res.get('dockerfile', res_name + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/Dockerfile.app.autogenerated'),
        'res_path': full_res_path,
        'env': env_vars,
    }


def register_compose_resources(service_config, ctx, runtime_flags, manifest_state):
    """Register all compose resources for a service."""
    service_name = service_config['name']
    service_path = service_config['path']
    should_enable = ctx['should_enable']
    write_file = ctx['write_file']
    compose_project_name = service_name + '-autogenerated'
    
    resource_manifests = manifest_state['resource_manifests']
    config_gen_resources = manifest_state['config_gen_resources']
    has_backend = _has_backend_resource(service_config, resource_manifests)
    infra_deps = _build_infra_dependencies(service_name, should_enable, ctx, has_backend)
    
    # Build map of all services for dependency resolution
    # This maps short names like 'identity' to full resource names
    all_services_map = {}
    all_services = ctx.get('all_services', [])
    for svc in all_services:
        svc_name = svc.get('name', '')
        if svc_name:
            all_services_map[svc_name] = svc
        # Also map resource names
        for res in svc.get('resources', []):
            res_name = res.get('name', '')
            if res_name:
                all_services_map[res_name] = svc

    service_entries = []
    resource_configs = []

    for res in service_config.get('resources', []):
        if _should_skip_frontend(res, should_enable):
            continue
        
        full_res_path = res.get('_service_path', service_path + '/' + res['name'])
        manifest = resource_manifests.get(res['name'], {})
        
        # Skip library type resources - they don't have Docker builds
        if manifest.get('appType') == 'library':
            print("DEBUG: Skipping library resource in compose: " + res['name'])
            continue
        
        if res.get('frontend', False):
            entry = _process_frontend_resource(res, manifest, full_res_path, service_path, service_name, should_enable)
        else:
            entry = _process_backend_resource(res, manifest, full_res_path, service_path, service_name, should_enable)
        
        service_entries.append(entry)
        resource_configs.append(_build_resource_config(
            res, manifest, service_config, full_res_path, infra_deps,
            config_gen_resources, resource_manifests, runtime_flags, all_services_map,
        ))

    Docker.app_compose(service_path, service_entries, write_file)
    docker_compose(
        service_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/docker-compose.app.autogenerated.yml',
        project_name=compose_project_name,
    )

    for compose_file in service_config.get('compose_files', []):
        if compose_file != 'autogenerated/docker-compose.app.autogenerated.yml':
            docker_compose(service_path + '/' + compose_file, project_name=compose_project_name)

    _register_dc_resources(resource_configs, service_path, compose_project_name, runtime_flags['auto_init_apps'])

    return {'compose_project_name': compose_project_name}


ComposeResourceRegistration = struct(
    register = register_compose_resources,
)

DEBUG = {}
