appName: inventory-management-backend
appType: backend
stack: inventory
port: 4005
apiPath: /api/inventory-management
features:
infisicalSecretPath: /services/inventory
replicas: 1
runtime: bun
sablier:
  displayName: Inventory Management Service
  enable: True
  refreshFrequency: 5s
  sessionDuration: 5m
  theme: hacker-terminal
