/**
 * TDK (Tilt Development Kit) Type Definitions
 *
 * Types for resource discovery and stack management.
 * Stacks are discovered dynamically from service.json files - no stack.master needed.
 */

/**
 * Represents a discovered resource from the Tilt infrastructure
 */
export interface DiscoveredResource {
  /** Resource name (from appName in service.json or directory name) */
  name: string;

  /** Full path to resource directory */
  path: string;

  /** Path to service.json file */
  configPath: string;

  /** Parsed service.json content */
  config?: ResourceConfig;

  /**
   * The stack this resource belongs to (from service.json).
   * Each resource can belong to exactly one stack.
   */
  stack?: string;

  /** Resource port (extracted from config for convenience) */
  port?: number;

  /** Resource type (extracted from config for convenience) */
  type?: string;
}

/**
 * Partial service.json structure (only fields TDK cares about)
 */
export interface ResourceConfig {
  appName: string;
  appType: 'backend' | 'frontend' | 'library' | 'sdk' | 'worker' | 'migrator';
  stack?: string;
  port?: number;
  replicas?: number;
  runtime: string;
  features?: string[];
  internalDependencies?: string[];
  dependencies?: string[];
  /**
   * Whether this resource is enabled for deployment.
   * Disabled resources are shown in the UI but marked as disabled.
   * Resources without this field default to enabled (true).
   */
  enabled?: boolean;
  /**
   * Base path for Traefik routing.
   * Used to construct the public URL: http://{host}/{basePath}
   * Example: "/identity-management"
   */
  basePath?: string;
  /**
   * Backend resource name this frontend connects to.
   */
  backendName?: string;
}

/**
 * Represents a discovered stack (aggregated from resources)
 */
export interface DiscoveredStack {
  /** Stack name */
  name: string;

  /** Human-readable description (derived from resources or metadata) */
  description?: string;

  /** Resources that belong to this stack */
  resources: DiscoveredResource[];

  /** Number of resources in the stack */
  resourceCount: number;
}

/**
 * Options passed to CLI commands
 */
export interface CLIOptions {
  /** Enable verbose output */
  verbose?: boolean;
}

/**
 * Result of executing a tilt command
 */
export interface TiltCommandResult {
  /** Exit code from tilt process */
  exitCode: number;

  /** stdout output */
  stdout: string;

  /** stderr output */
  stderr: string;
}

// Metadata types

/**
 * File type classification for autogenerated files
 */
export type FileType = 'docker' | 'tilt' | 'config' | 'prisma' | 'generated' | 'unknown';

/**
 * Represents an autogenerated file in a resource directory
 */
export interface AutogeneratedFile {
  /** File name */
  name: string;
  /** Full file path */
  path: string;
  /** File type classification */
  type: FileType;
  /** File size in bytes */
  size: number;
  /** Last modified timestamp (ISO 8601) */
  lastModified: string;
}

/**
 * Resource type classification
 * Canonical type for all resource classifications
 */
export type ResourceType = 'frontend' | 'backend' | 'library' | 'sdk' | 'worker' | 'migrator';

/**
 * Runtime status of a resource
 */
export type ResourceStatus = 'ready' | 'pending' | 'error' | 'unknown';

/**
 * Metadata for a discovered resource
 * This is the canonical version - consolidated from services.ts and DetailPanel.tsx
 */
export interface ResourceMetadata {
  /** Resource name */
  name: string;
  /** Stack this resource belongs to */
  stack?: string;
  /** Resource type classification */
  type: ResourceType;
  /** Assigned port number */
  port?: number;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last modified timestamp (ISO 8601) */
  lastModified: string;
  /** Dependencies this resource has */
  dependencies: string[];
  /** Whether the resource has a Dockerfile */
  hasDockerfile: boolean;
  /** Whether the resource has a Tiltfile */
  hasTiltfile: boolean;
  /** Whether the resource has docker-compose configuration */
  hasDockerCompose: boolean;
  /** List of autogenerated files */
  autogeneratedFiles: AutogeneratedFile[];
  /** Current runtime status */
  status: ResourceStatus;
}

/**
 * Overall health status of a stack
 */
export type StackHealthStatus = 'healthy' | 'degraded' | 'error' | 'unknown';

/**
 * Metadata for a discovered stack
 * This is the canonical version - consolidated from services.ts and DetailPanel.tsx
 */
export interface StackMetadata {
  /** Stack name */
  name: string;
  /** Number of resources in the stack */
  resourceCount: number;
  /** Stack creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last modification timestamp (ISO 8601) */
  lastModified: string;
  /** Metadata for all resources in the stack */
  resources: ResourceMetadata[];
  /** Overall health status */
  overallStatus: StackHealthStatus;
}

/**
 * Runtime status of a Tilt resource
 */
export type TiltRuntimeStatus = 'running' | 'pending' | 'error' | 'unknown';

/**
 * Build status of a Tilt resource
 */
export type TiltBuildStatus = 'ok' | 'error' | 'in_progress' | 'unknown';

/**
 * Status information for a Tilt resource
 */
export interface TiltResourceStatus {
  /** Current runtime status */
  runtimeStatus: TiltRuntimeStatus;
  /** Current build status */
  buildStatus: TiltBuildStatus;
  /** Timestamp of last successful build */
  lastBuildTime: string | null;
  /** Timestamp of current build (if building) */
  currentBuildTime: string | null;
  /** Whether the resource is available/registered in Tilt */
  available: boolean;
}

// ============================================================================
// JSON Value Types
// ============================================================================

/**
 * JSON-compatible value types for configuration overrides
 * Used for project configuration and template generation
 */
export type JsonValue = string | number | boolean | null | JsonArray | JsonObject;

/**
 * JSON array type
 */
export interface JsonArray extends Array<JsonValue> {}

/**
 * JSON object type
 */
export interface JsonObject extends Record<string, JsonValue> {}

// ============================================================================
// Project Configuration Types
// ============================================================================

/**
 * Stack definition within project configuration
 */
export interface ProjectStackDefinition {
  name: string;
  description: string;
  services: string[];
}

/**
 * Optional infrastructure configuration
 */
export interface ProjectOptionalInfra {
  monitoring: boolean;
  elk: boolean;
  debezium: boolean;
  golden_image: boolean;
}

/**
 * Discovery configuration for project scanning
 */
export interface ProjectDiscovery {
  paths: string[];
}

/**
 * Project configuration structure (from .tdk/project.json)
 * This is the canonical type - consolidated from template-engine.ts
 */
export interface ProjectConfig {
  version: string;
  project: {
    name: string;
    version: string;
  };
  stacks: {
    pre_alpha: ProjectStackDefinition;
    alpha: ProjectStackDefinition;
    beta: ProjectStackDefinition;
    out_of_scope: ProjectStackDefinition;
  };
  optional_infra: ProjectOptionalInfra;
  discovery: ProjectDiscovery;
  overrides?: Record<string, JsonValue>;
}

// ============================================================================
// UI Component Types
// ============================================================================

/**
 * Props for tooltip components
 * Consolidated from Tooltip.tsx and Accessible.tsx
 */
export interface TooltipProps {
  /** Tooltip content text */
  content: string;
  /** Optional keyboard shortcut to display */
  shortcut?: string;
  /** Whether the tooltip is currently visible */
  visible: boolean;
  /** Maximum width for tooltip content wrapping */
  maxWidth?: number;
}
