/** TDK Type Definitions */

export interface DiscoveredResource {
  name: string;
  path: string;
  configPath: string;
  config?: ResourceConfig;
  stack?: string;
  port?: number;
  type?: string;
}

export interface ResourceConfig {
  appName: string;
  appType: 'backend' | 'frontend' | 'library' | 'sdk' | 'worker' | 'migrator';
  stack?: string;
  port?: number;
  replicas?: number;
  runtime: string;
  features?: string[];
  internalDependencies?: string[];
  dependencies?: string[];
  enabled?: boolean;
  basePath?: string;
  backendName?: string;
}

export interface DiscoveredStack {
  name: string;
  description?: string;
  resources: DiscoveredResource[];
  resourceCount: number;
}

export interface TiltCommandResult {
  exitCode: number;
  stdout: string;
  stderr: string;
}

export type FileType = 'docker' | 'tilt' | 'config' | 'prisma' | 'generated' | 'unknown';

export interface AutogeneratedFile {
  name: string;
  path: string;
  type: FileType;
  size: number;
  lastModified: string;
}

export type ResourceType = 'frontend' | 'backend' | 'library' | 'sdk' | 'worker' | 'migrator';

export type ResourceStatus = 'ready' | 'pending' | 'error' | 'unknown';

export interface ResourceMetadata {
  name: string;
  stack?: string;
  type: ResourceType;
  port?: number;
  createdAt: string;
  lastModified: string;
  dependencies: string[];
  hasDockerfile: boolean;
  hasTiltfile: boolean;
  hasDockerCompose: boolean;
  autogeneratedFiles: AutogeneratedFile[];
  status: ResourceStatus;
}

export type StackHealthStatus = 'healthy' | 'degraded' | 'error' | 'unknown';

export interface StackMetadata {
  name: string;
  resourceCount: number;
  createdAt: string;
  lastModified: string;
  resources: ResourceMetadata[];
  overallStatus: StackHealthStatus;
}

export type TiltRuntimeStatus = 'running' | 'pending' | 'error' | 'unknown';

export type TiltBuildStatus = 'ok' | 'error' | 'in_progress' | 'unknown';

export interface TiltResourceStatus {
  runtimeStatus: TiltRuntimeStatus;
  buildStatus: TiltBuildStatus;
  lastBuildTime: string | null;
  currentBuildTime: string | null;
  available: boolean;
}

/**
 * JSON-compatible value types for configuration overrides
 * Used for project configuration and template generation
 */
export type JsonValue = string | number | boolean | null | JsonArray | JsonObject;

/**
 * JSON array type (internal use only)
 */
interface JsonArray extends Array<JsonValue> {}

/**
 * JSON object type (internal use only)
 */
interface JsonObject extends Record<string, JsonValue> {}

/**
 * Stack definition within project configuration
 */
export interface ProjectStackDefinition {
  name: string;
  description: string;
  services: string[];
}

/**
 * Optional infrastructure configuration
 */
export interface ProjectOptionalInfra {
  monitoring: boolean;
  elk: boolean;
  debezium: boolean;
  golden_image: boolean;
}

/**
 * Discovery configuration for project scanning
 */
export interface ProjectDiscovery {
  paths: string[];
}

/**
 * Project configuration structure (from .tdk/project.json)
 * This is the canonical type - consolidated from template-engine.ts
 */
export interface ProjectConfig {
  version: string;
  project: {
    name: string;
    version: string;
  };
  stacks: {
    pre_alpha: ProjectStackDefinition;
    alpha: ProjectStackDefinition;
    beta: ProjectStackDefinition;
    out_of_scope: ProjectStackDefinition;
  };
  optional_infra: ProjectOptionalInfra;
  discovery: ProjectDiscovery;
  overrides?: Record<string, JsonValue>;
}

// UI Component Types

/**
 * Props for tooltip components
 * Consolidated from Tooltip.tsx and Accessible.tsx
 */
export interface TooltipProps {
  /** Tooltip content text */
  content: string;
  /** Optional keyboard shortcut to display */
  shortcut?: string;
  /** Whether the tooltip is currently visible */
  visible: boolean;
  /** Maximum width for tooltip content wrapping */
  maxWidth?: number;
}

/**
 * Represents a node in a file tree structure
 * Used by FileTree component and file discovery utilities
 */
export interface FileNode {
  /** Display name of the file or directory */
  name: string;
  /** Absolute path to the file or directory */
  path: string;
  /** Whether this is a directory or file */
  type: 'directory' | 'file';
  /** Classification of file type for icons/styling */
  fileType?: FileType;
  /** Child nodes if this is a directory */
  children?: FileNode[];
  /** File size in bytes (undefined for directories) */
  size?: number;
  /** Last modified timestamp ISO string */
  lastModified?: string;
}

/**
 * Standard validation result pattern used across the CLI
 * Used by resource name validation, stack name validation, etc.
 */
export interface ValidationResult {
  /** Whether validation passed */
  valid: boolean;
  /** Error message if validation failed */
  error?: string;
}

// Health Check Types

/**
 * Result of a health check performed by the doctor command
 * Consolidated from doctor.ts for use across health check utilities
 */
export interface CheckResult {
  /** Name of the check (e.g., "Docker", "Bun") */
  name: string;
  /** Whether the check passed */
  didPass: boolean;
  /** Human-readable status message */
  message: string;
  /** Optional fix instructions if check failed */
  fix?: string;
}

/**
 * Represents a service URL in Traefik-routed networks
 * Used by the networks command for displaying service endpoints
 */
export interface ServiceUrl {
  /** Service/resource name */
  name: string;
  /** Stack the service belongs to (if any) */
  stack?: string;
  /** Base path for routing (e.g., "/api") */
  basePath: string;
  /** Full URL to access the service */
  url: string;
  /** Port the service listens on (if known) */
  port?: number;
  /** Current service status */
  status: 'running' | 'stopped' | 'unknown';
}

// ============================================================================
// UI Component Shared Types
// ============================================================================

/**
 * Standard select item for dropdown/select components
 * Used by ResourceSelectInput and other selection UI components
 */
export interface SelectItem {
  /** Display label for the item */
  label: string;
  /** Unique value/identifier */
  value: string;
}
