/** TDK Type Definitions */

export interface DiscoveredResource {
  name: string;
  path: string;
  configPath: string;
  config?: ResourceConfig;
  stack?: string;
  port?: number;
  type?: string;
}

export interface ResourceConfig {
  appName: string;
  appType: 'backend' | 'frontend' | 'library' | 'sdk' | 'worker' | 'migrator';
  stack?: string;
  port?: number;
  replicas?: number;
  runtime: string;
  features?: string[];
  internalDependencies?: string[];
  dependencies?: string[];
  enabled?: boolean;
  basePath?: string;
  backendName?: string;
}

export interface DiscoveredStack {
  name: string;
  description?: string;
  resources: DiscoveredResource[];
  resourceCount: number;
}

export interface CLIOptions {
  verbose?: boolean;
}

export interface TiltCommandResult {
  exitCode: number;
  stdout: string;
  stderr: string;
}

// Metadata types

export type FileType = 'docker' | 'tilt' | 'config' | 'prisma' | 'generated' | 'unknown';

export interface AutogeneratedFile {
  name: string;
  path: string;
  type: FileType;
  size: number;
  lastModified: string;
}

export type ResourceType = 'frontend' | 'backend' | 'library' | 'sdk' | 'worker' | 'migrator';

export type ResourceStatus = 'ready' | 'pending' | 'error' | 'unknown';

export interface ResourceMetadata {
  name: string;
  stack?: string;
  type: ResourceType;
  port?: number;
  createdAt: string;
  lastModified: string;
  dependencies: string[];
  hasDockerfile: boolean;
  hasTiltfile: boolean;
  hasDockerCompose: boolean;
  autogeneratedFiles: AutogeneratedFile[];
  status: ResourceStatus;
}

export type StackHealthStatus = 'healthy' | 'degraded' | 'error' | 'unknown';

export interface StackMetadata {
  name: string;
  resourceCount: number;
  createdAt: string;
  lastModified: string;
  resources: ResourceMetadata[];
  overallStatus: StackHealthStatus;
}

export type TiltRuntimeStatus = 'running' | 'pending' | 'error' | 'unknown';

export type TiltBuildStatus = 'ok' | 'error' | 'in_progress' | 'unknown';

export interface TiltResourceStatus {
  runtimeStatus: TiltRuntimeStatus;
  buildStatus: TiltBuildStatus;
  lastBuildTime: string | null;
  currentBuildTime: string | null;
  available: boolean;
}

// ============================================================================
// JSON Value Types
// ============================================================================

/**
 * JSON-compatible value types for configuration overrides
 * Used for project configuration and template generation
 */
export type JsonValue = string | number | boolean | null | JsonArray | JsonObject;

/**
 * JSON array type
 */
export interface JsonArray extends Array<JsonValue> {}

/**
 * JSON object type
 */
export interface JsonObject extends Record<string, JsonValue> {}

// ============================================================================
// Project Configuration Types
// ============================================================================

/**
 * Stack definition within project configuration
 */
export interface ProjectStackDefinition {
  name: string;
  description: string;
  services: string[];
}

/**
 * Optional infrastructure configuration
 */
export interface ProjectOptionalInfra {
  monitoring: boolean;
  elk: boolean;
  debezium: boolean;
  golden_image: boolean;
}

/**
 * Discovery configuration for project scanning
 */
export interface ProjectDiscovery {
  paths: string[];
}

/**
 * Project configuration structure (from .tdk/project.json)
 * This is the canonical type - consolidated from template-engine.ts
 */
export interface ProjectConfig {
  version: string;
  project: {
    name: string;
    version: string;
  };
  stacks: {
    pre_alpha: ProjectStackDefinition;
    alpha: ProjectStackDefinition;
    beta: ProjectStackDefinition;
    out_of_scope: ProjectStackDefinition;
  };
  optional_infra: ProjectOptionalInfra;
  discovery: ProjectDiscovery;
  overrides?: Record<string, JsonValue>;
}

// ============================================================================
// UI Component Types
// ============================================================================

/**
 * Props for tooltip components
 * Consolidated from Tooltip.tsx and Accessible.tsx
 */
export interface TooltipProps {
  /** Tooltip content text */
  content: string;
  /** Optional keyboard shortcut to display */
  shortcut?: string;
  /** Whether the tooltip is currently visible */
  visible: boolean;
  /** Maximum width for tooltip content wrapping */
  maxWidth?: number;
}
