/**
 * tdk ui command - Interactive Terminal UI using Ink
 *
 * A powerful TUI for managing stacks, services, and autogenerated files.
 * Uses Ink (React for CLIs) for smooth, efficient rendering.
 */

import { Command } from 'commander';
import React, { useState, useMemo, useEffect } from 'react';
import { render, Box, Text, useInput, useApp, useStdout, useStdin } from 'ink';
import SelectInput from 'ink-select-input';
import { discoverStacks, discoverServices, findProjectRoot } from '../utils/services.js';
import { isTiltAvailable } from '../utils/tilt.js';

// Status Bar Component
const StatusBar: React.FC<{mode: string; stacks: number; services: number; inStack: number}> = ({ 
  mode, stacks, services, inStack 
}) => (
  <Box 
    height={3} 
    borderStyle="single" 
    borderColor="gray" 
    paddingX={1}
    flexDirection="column"
  >
    <Box justifyContent="space-between">
      <Text color="cyan" bold>Mode: {mode.toUpperCase()}</Text>
      <Text color="green">● {inStack} in stack</Text>
      <Text color="yellow">○ {services - inStack} no stack</Text>
    </Box>
    <Box justifyContent="space-between">
      <Text color="gray">Stacks: {stacks}</Text>
      <Text color="gray">Services: {services}</Text>
      <Text color="gray">[↑↓] Navigate | [Enter/Space] Select | [Tab] Mode | [q] Quit</Text>
    </Box>
  </Box>
);

// Main UI Component
const TUIApp: React.FC = () => {
  const { exit } = useApp();
  const { stdout } = useStdout();
  const { stdin, setRawMode } = useStdin();
  const [mode, setMode] = useState<'stacks' | 'services' | 'files'>('stacks');
  const [selectedStack, setSelectedStack] = useState<string | null>(null);
  const [message, setMessage] = useState<string>('');
  const [highlightedIndex, setHighlightedIndex] = useState(0);

  const projectRoot = findProjectRoot() || 'unknown';
  const stacks = discoverStacks();
  const services = discoverServices();
  
  // Calculate stats
  const stats = useMemo(() => {
    const inStack = services.filter(s => s.stack).length;
    return {
      totalStacks: stacks.length,
      totalServices: services.length,
      inStack,
      noStack: services.length - inStack
    };
  }, [stacks, services]);

  // Build menu items based on mode
  const getItems = () => {
    if (mode === 'stacks') {
      return stacks.map(stack => ({
        label: `${stack.name} (${stack.services.length} services)`,
        value: stack.name,
        services: stack.services.map(s => s.name)
      }));
    } else if (mode === 'services') {
      return services.map(s => ({
        label: `${s.domain}/${s.name} ${s.stack ? `[${s.stack}]` : '[no stack]'}`,
        value: s.name,
        domain: s.domain,
        stack: s.stack,
        enabled: true
      }));
    }
    return [];
  };

  const items = getItems();

  // Enable raw mode for keyboard input
  useEffect(() => {
    setRawMode(true);
    return () => {
      setRawMode(false);
    };
  }, [setRawMode]);

  // Handle keyboard input
  useInput((input, key) => {
    if (input === 'q' || key.escape) {
      exit();
    }
    if (key.tab) {
      setMode(prev => {
        const modes: typeof mode[] = ['stacks', 'services', 'files'];
        const idx = modes.indexOf(prev);
        return modes[(idx + 1) % modes.length];
      });
    }
    // Spacebar to select current item
    if (input === ' ') {
      // Get currently highlighted item and select it
      const currentItem = items[highlightedIndex];
      if (currentItem) {
        handleSelect(currentItem);
      }
    }
    // Arrow navigation with wrapping
    if (key.upArrow) {
      setHighlightedIndex(prev => (prev > 0 ? prev - 1 : items.length - 1));
    }
    if (key.downArrow) {
      setHighlightedIndex(prev => (prev < items.length - 1 ? prev + 1 : 0));
    }
    // Home/End keys
    if (key.return) {
      const currentItem = items[highlightedIndex];
      if (currentItem) {
        handleSelect(currentItem);
      }
    }
  });

  const handleSelect = (item: any) => {
    if (mode === 'stacks') {
      setSelectedStack(item.value);
      setMessage(`Selected stack: ${item.value} (${item.services.length} services)`);
      setTimeout(() => setMessage(''), 2000);
    } else if (mode === 'services') {
      setMessage(`Toggled: ${item.value}`);
      setTimeout(() => setMessage(''), 1500);
    }
  };

  return (
    <Box flexDirection="column" height={stdout.rows || 24}>
      {/* Header */}
      <Box backgroundColor="blue" paddingX={1} paddingY={0} height={1}>
        <Text bold color="white"> TDK Interactive UI </Text>
        <Text color="white" dimColor> | {projectRoot}</Text>
      </Box>
      
      {/* Message area */}
      {message && (
        <Box paddingX={1} height={1}>
          <Text color="green">✓ {message}</Text>
        </Box>
      )}

      {/* Content - takes remaining space */}
      <Box flexDirection="column" paddingX={1} flexGrow={1}>
        {mode === 'stacks' && (
          <>
            <Text bold underline>📦 Stacks ({stacks.length})</Text>
            <Box marginTop={1}>
              <SelectInput 
                items={items} 
                onSelect={handleSelect}
                initialIndex={highlightedIndex}
                indicatorComponent={({ isSelected }) => (
                  <Text color={isSelected ? 'cyan' : undefined}>{isSelected ? '▸ ' : '  '}</Text>
                )}
                itemComponent={({ isSelected, label }) => (
                  <Text color={isSelected ? 'cyan' : 'white'} bold={isSelected}>
                    {label}
                  </Text>
                )}
              />
            </Box>
            {selectedStack && (
              <Box marginTop={1} flexDirection="column">
                <Text color="gray">Services in {selectedStack}:</Text>
                {stacks.find(s => s.name === selectedStack)?.services.map(s => (
                  <Text key={s.name} color="gray">  ├─ {s.name} ({s.domain})</Text>
                ))}
              </Box>
            )}
          </>
        )}

        {mode === 'services' && (
          <>
            <Text bold underline>🔧 Services ({services.length})</Text>
            <Text color="gray">{stats.inStack} in stack | {stats.noStack} no stack</Text>
            <Box marginTop={1}>
              <SelectInput 
                items={items} 
                onSelect={handleSelect}
                initialIndex={highlightedIndex}
                indicatorComponent={({ isSelected }) => (
                  <Text color={isSelected ? 'cyan' : undefined}>{isSelected ? '▸ ' : '  '}</Text>
                )}
                itemComponent={({ isSelected, label }) => (
                  <Text color={isSelected ? 'cyan' : 'white'} bold={isSelected}>
                    {label}
                  </Text>
                )}
              />
            </Box>
          </>
        )}

        {mode === 'files' && (
          <>
            <Text bold underline>📁 Autogenerated Files</Text>
            <Box marginTop={1}>
              <Text color="yellow">File browser coming soon...</Text>
            </Box>
          </>
        )}
      </Box>

      {/* Sticky Footer with Status */}
      <Box marginTop={1}>
        <StatusBar 
          mode={mode} 
          stacks={stats.totalStacks} 
          services={stats.totalServices}
          inStack={stats.inStack}
        />
      </Box>
    </Box>
  );
};

export const uiCommand = new Command('ui')
  .description('Interactive TUI for managing stacks and services (Neon-style)')
  .alias('interactive')
  .option('-v, --verbose', 'Enable verbose output', false)
  .action(async () => {
    try {
      // Check tilt is available
      const tiltAvailable = await isTiltAvailable();
      if (!tiltAvailable) {
        console.error('Error: tilt CLI not found. Make sure Tilt is installed.');
        process.exit(1);
      }

      const projectRoot = findProjectRoot();
      if (!projectRoot) {
        console.error('Error: Could not find project root (no Tiltfile found).');
        process.exit(1);
      }

      // Install ink-select-input if needed
      try {
        await import('ink-select-input');
      } catch {
        console.log('Installing dependencies...');
        const { execSync } = await import('child_process');
        execSync('bun add ink-select-input', { cwd: process.cwd(), stdio: 'inherit' });
      }

      // Render the Ink app
      render(<TUIApp />);

    } catch (err) {
      console.error(`Error: ${err}`);
      process.exit(1);
    }
  });
