/**
 * tdk ui command - Interactive Terminal UI using Ink
 *
 * AWS CloudFormation/CDK-style tabbed interface for managing stacks and services.
 * Tabs: Overview, Resources, Events, Autogenerated Files, Configuration
 */

import { Command } from 'commander';
import React, { useState, useMemo, useEffect, useCallback } from 'react';
import { render, Box, Text, useInput, useApp, useStdout, useStdin, type Key } from 'ink';
import SelectInput from 'ink-select-input';
import { stdout as processStdout, stdin as processStdin } from 'node:process';
import { 
  discoverStacks, 
  discoverServices, 
  findProjectRoot,
  getServiceMetadata,
  getStackMetadata,
  clearMetadataCache,
  type ServiceMetadata,
  type StackMetadata,
} from '../utils/services.js';
import { isTiltAvailable } from '../utils/tilt.js';
import { TabBar, type TabId, DetailPanel, ResourceTable, FileTree, type FileNode } from '../components/index.js';

// Help Panel Component
const HelpPanel: React.FC<{ onClose: () => void }> = ({ onClose }) => (
  <Box 
    borderStyle="double" 
    borderColor="cyan"
    paddingX={2}
    paddingY={1}
    flexDirection="column"
    width={60}
  >
    <Text bold color="cyan" underline>Keyboard Shortcuts</Text>
    <Box marginY={1} flexDirection="column">
      <Text><Text bold>Navigation:</Text></Text>
      <Text>  Mouse   Click to select items/tabs</Text>
      <Text>  ↑/↓     Navigate list items</Text>
      <Text>  Enter   Select item / Open detail</Text>
      <Text>  Space   Toggle expand (tree view)</Text>
      <Text>  Tab     Next tab</Text>
      <Text>  Shift+Tab Previous tab</Text>
      
      <Text><Text bold>Tabs:</Text></Text>
      <Text>  1       Overview tab</Text>
      <Text>  2       Resources tab</Text>
      <Text>  3       Events tab</Text>
      <Text>  4       Files tab</Text>
      <Text>  5       Config tab</Text>
      
      <Text><Text bold>Actions:</Text></Text>
      <Text>  a       Toggle all/pre-alpha services</Text>
      <Text>  m       Toggle mouse support</Text>
      <Text>  r       Refresh data</Text>
      <Text>  /       Search/filter</Text>
      <Text>  ?       Show this help</Text>
      <Text>  q/Esc   Quit / Back</Text>
    </Box>
    <Box marginTop={1}>
      <Text color="gray" dimColor>Press any key to close...</Text>
    </Box>
  </Box>
);

// Main UI Component
const TUIApp: React.FC = () => {
  const { exit } = useApp();
  const { stdout } = useStdout();
  const { stdin, setRawMode } = useStdin();
  
  // State
  const [activeTab, setActiveTab] = useState<TabId>('overview');
  const [selectedStack, setSelectedStack] = useState<string | null>(null);
  const [selectedService, setSelectedService] = useState<string | null>(null);
  const [message, setMessage] = useState<string>('');
  const [highlightedIndex, setHighlightedIndex] = useState(0);
  const [showHelp, setShowHelp] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [isSearching, setIsSearching] = useState(false);
  const [showAllServices, setShowAllServices] = useState(false);
  const [terminalWidth, setTerminalWidth] = useState(stdout.columns || 120);
  const [expandedNodes, setExpandedNodes] = useState<Set<string>>(new Set());
  const [selectedFile, setSelectedFile] = useState<string | null>(null);
  const [filePreview, setFilePreview] = useState<string | null>(null);
  const [mouseEnabled, setMouseEnabled] = useState(true);
  const [mouseClickY, setMouseClickY] = useState<number | null>(null);

  // Data
  const projectRoot = findProjectRoot() || 'unknown';
  const stacks = discoverStacks({ preAlphaOnly: !showAllServices });
  const services = discoverServices({ preAlphaOnly: !showAllServices });
  
  // Get metadata for selected stack
  const selectedStackData = useMemo(() => {
    if (!selectedStack) return null;
    const stack = stacks.find(s => s.name === selectedStack);
    if (!stack) return null;
    return {
      stack,
      metadata: getStackMetadata(stack),
    };
  }, [selectedStack, stacks]);

  // Get metadata for selected service
  const selectedServiceData = useMemo(() => {
    if (!selectedService) return null;
    const service = services.find(s => s.name === selectedService);
    if (!service) return null;
    return {
      service,
      metadata: getServiceMetadata(service),
    };
  }, [selectedService, services]);

  // Filtered items based on search
  const filteredStacks = useMemo(() => {
    if (!searchQuery) return stacks;
    return stacks.filter(s => 
      s.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      s.services.some(svc => svc.name.toLowerCase().includes(searchQuery.toLowerCase()))
    );
  }, [stacks, searchQuery]);

  const filteredServices = useMemo(() => {
    if (!searchQuery) return services;
    return services.filter(s => 
      s.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (s.domain || '').toLowerCase().includes(searchQuery.toLowerCase())
    );
  }, [services, searchQuery]);

  // Build menu items for current tab
  const getItems = useCallback(() => {
    if (activeTab === 'overview') {
      return filteredStacks.map(stack => ({
        label: `${stack.name} (${stack.services.length} services)`,
        value: stack.name,
      }));
    }
    
    if (activeTab === 'resources') {
      if (selectedStackData) {
        // Show services in selected stack
        return selectedStackData.stack.services.map(s => ({
          label: `${s.name} [${s.domain}]`,
          value: s.name,
        }));
      }
      return filteredStacks.map(stack => ({
        label: `${stack.name} (${stack.services.length} services)`,
        value: stack.name,
      }));
    }
    
    if (activeTab === 'files') {
      if (selectedServiceData) {
        // Show autogenerated files for selected service
        return selectedServiceData.metadata.autogeneratedFiles.map(f => ({
          label: `${f.name} (${f.type})`,
          value: f.path,
        }));
      }
      return filteredServices.map(s => ({
        label: `${s.domain}/${s.name}`,
        value: s.name,
      }));
    }
    
    if (activeTab === 'config') {
      return filteredServices.map(s => ({
        label: `${s.domain}/${s.name} ${s.stack ? `[${s.stack}]` : ''}`,
        value: s.name,
      }));
    }
    
    return [];
  }, [activeTab, filteredStacks, filteredServices, selectedStackData, selectedServiceData]);

  const items = getItems();

  // Handle selection (defined early for useEffect dependencies)
  const handleSelect = useCallback((item: { label: string; value: string }) => {
    if (activeTab === 'overview') {
      setSelectedStack(item.value);
      setSelectedService(null);
      setMessage(`Selected stack: ${item.value}`);
      setTimeout(() => setMessage(''), 2000);
    } else if (activeTab === 'resources') {
      if (selectedStack && !selectedService) {
        // Selecting a service within a stack
        setSelectedService(item.value);
        setMessage(`Selected service: ${item.value}`);
        setTimeout(() => setMessage(''), 2000);
      } else {
        // Selecting a stack
        setSelectedStack(item.value);
        setSelectedService(null);
      }
    } else if (activeTab === 'files') {
      if (selectedService) {
        // Selecting a file
        setSelectedFile(item.value);
        setMessage(`Selected file: ${item.label}`);
        setTimeout(() => setMessage(''), 2000);
      } else {
        // Selecting a service
        setSelectedService(item.value);
        setMessage(`Selected service: ${item.value}`);
        setTimeout(() => setMessage(''), 2000);
      }
    } else if (activeTab === 'config') {
      setSelectedService(item.value);
      setMessage(`Viewing config for: ${item.value}`);
      setTimeout(() => setMessage(''), 2000);
    }
  }, [activeTab, selectedStack, selectedService, setSelectedStack, setSelectedService, setSelectedFile, setMessage]);

  // Enable raw mode and mouse support
  useEffect(() => {
    setRawMode(true);
    
    // Enable mouse reporting (X11 mode - button press and release)
    if (mouseEnabled && processStdout.isTTY) {
      processStdout.write('\x1b[?1000h\x1b[?1002h\x1b[?1015h\x1b[?1006h');
    }
    
    return () => {
      setRawMode(false);
      // Disable mouse reporting
      if (processStdout.isTTY) {
        processStdout.write('\x1b[?1000l\x1b[?1002l\x1b[?1015l\x1b[?1006l');
      }
    };
  }, [setRawMode, mouseEnabled]);

  // Handle terminal resize
  useEffect(() => {
    const handleResize = () => {
      setTerminalWidth(stdout.columns || 120);
    };
    
    stdout.on('resize', handleResize);
    return () => {
      stdout.off('resize', handleResize);
    };
  }, [stdout]);

  // Handle mouse clicks
  useEffect(() => {
    if (!mouseEnabled || !stdin) return;
    
    const handleMouseData = (data: Buffer) => {
      const str = data.toString();
      
      // Check for mouse event sequences
      // X10 mode: \x1b[M<btn><col><row> (3 chars after M)
      // SGR 1006 mode: \x1b[<btn;x;yM (press) or \x1b[<btn;x;ym (release)
      
      const sgrMatch = str.match(/\x1b\[<(\d+);(\d+);(\d+)(M|m)/);
      if (sgrMatch) {
        const button = parseInt(sgrMatch[1], 10);
        const x = parseInt(sgrMatch[2], 10);
        const y = parseInt(sgrMatch[3], 10);
        const isPress = sgrMatch[4] === 'M';
        
        // Button 0 = left click, 1 = middle, 2 = right
        if (isPress && button === 0) {
          setMouseClickY(y);
          
          // Calculate which list item was clicked
          // Header is at rows 1-3, tab bar at row 4, content starts around row 6
          const listStartY = 6;
          const clickedIndex = y - listStartY;
          
          // Check if click is within the list area (left side, not in sidebar)
          // List starts at column 1, width varies based on sidebar visibility
          const listStartX = 1;
          const listWidth = showSidebar ? terminalWidth - 50 : terminalWidth - 4;
          
          if (clickedIndex >= 0 && clickedIndex < items.length && x >= listStartX && x <= listStartX + listWidth) {
            setHighlightedIndex(clickedIndex);
            const clickedItem = items[clickedIndex];
            if (clickedItem) {
              handleSelect(clickedItem);
            }
          }
          
          // Check for tab clicks (tab bar is at row 4)
          if (y === 4) {
            const tabWidth = Math.floor(terminalWidth / 5);
            const clickedTab = Math.floor((x - 1) / tabWidth);
            if (clickedTab >= 0 && clickedTab < 5) {
              const tabs: TabId[] = ['overview', 'resources', 'events', 'files', 'config'];
              setActiveTab(tabs[clickedTab]);
            }
          }
        }
        return;
      }
      
      // X10 mode: \x1b[M followed by 3 bytes
      const x10Match = str.match(/\x1b\[M(.)(.)(.)/);
      if (x10Match) {
        const button = x10Match[1].charCodeAt(0) - 32;
        const col = x10Match[2].charCodeAt(0) - 32;
        const row = x10Match[3].charCodeAt(0) - 32;
        
        if (button === 0) { // Left click
          setMouseClickY(row);
          const listStartY = 6;
          const clickedIndex = row - listStartY;
          
          // Check if click is within the list area (left side, not in sidebar)
          const listStartX = 1;
          const listWidth = showSidebar ? terminalWidth - 50 : terminalWidth - 4;
          
          if (clickedIndex >= 0 && clickedIndex < items.length && col >= listStartX && col <= listStartX + listWidth) {
            setHighlightedIndex(clickedIndex);
            const clickedItem = items[clickedIndex];
            if (clickedItem) {
              handleSelect(clickedItem);
            }
          }
        }
      }
    };
    
    stdin.on('data', handleMouseData);
    return () => {
      stdin.off('data', handleMouseData);
    };
  }, [mouseEnabled, stdin, items, terminalWidth, showSidebar, setHighlightedIndex, setActiveTab, handleSelect]);

  // Keyboard handling
  useInput((input, key) => {
    // Help panel
    if (showHelp) {
      setShowHelp(false);
      return;
    }

    // Search mode
    if (isSearching) {
      if (key.return) {
        setIsSearching(false);
        return;
      }
      if (key.escape) {
        setIsSearching(false);
        setSearchQuery('');
        return;
      }
      if (key.backspace || key.delete) {
        setSearchQuery(prev => prev.slice(0, -1));
        return;
      }
      if (input && !key.ctrl && !key.meta) {
        setSearchQuery(prev => prev + input);
        return;
      }
      return;
    }

    // Global shortcuts
    if (input === 'q' && !key.ctrl && !key.meta) {
      exit();
      return;
    }
    
    if (key.escape) {
      if (filePreview) {
        setFilePreview(null);
        return;
      }
      if (selectedFile) {
        setSelectedFile(null);
        return;
      }
      if (selectedService) {
        setSelectedService(null);
        return;
      }
      if (selectedStack) {
        setSelectedStack(null);
        return;
      }
      exit();
      return;
    }

    if (input === '?') {
      setShowHelp(true);
      return;
    }

    if (input === 'a') {
      setShowAllServices(prev => !prev);
      setMessage(showAllServices ? 'Showing pre-alpha services only' : 'Showing all services');
      setTimeout(() => setMessage(''), 1500);
      return;
    }

    if (input === 'm') {
      setMouseEnabled(prev => {
        const newState = !prev;
        setMessage(newState ? 'Mouse support enabled' : 'Mouse support disabled');
        return newState;
      });
      setTimeout(() => setMessage(''), 1500);
      return;
    }

    if (input === 'r') {
      clearMetadataCache();
      setMessage('Data refreshed');
      setTimeout(() => setMessage(''), 1500);
      return;
    }

    if (input === '/') {
      setIsSearching(true);
      setSearchQuery('');
      setMessage('Search: ');
      return;
    }

    // Tab switching
    if (key.tab) {
      const tabs: TabId[] = ['overview', 'resources', 'events', 'files', 'config'];
      const currentIdx = tabs.indexOf(activeTab);
      const nextIdx = key.shift 
        ? (currentIdx - 1 + tabs.length) % tabs.length 
        : (currentIdx + 1) % tabs.length;
      setActiveTab(tabs[nextIdx]);
      setHighlightedIndex(0);
      return;
    }

    // Direct tab access (1-5)
    if (/^[1-5]$/.test(input)) {
      const tabMap: Record<string, TabId> = {
        '1': 'overview',
        '2': 'resources',
        '3': 'events',
        '4': 'files',
        '5': 'config',
      };
      setActiveTab(tabMap[input]);
      setHighlightedIndex(0);
      return;
    }

    // Navigation
    if (key.upArrow) {
      setHighlightedIndex(prev => (prev > 0 ? prev - 1 : items.length - 1));
    }
    if (key.downArrow) {
      setHighlightedIndex(prev => (prev < items.length - 1 ? prev + 1 : 0));
    }
    if (key.return || input === ' ') {
      const currentItem = items[highlightedIndex];
      if (currentItem) {
        handleSelect(currentItem);
      }
      return;
    }
  });

  // Build file tree for Files tab
  const fileTreeNodes: FileNode[] = useMemo(() => {
    if (selectedServiceData) {
      return [{
        name: selectedServiceData.service.name,
        path: selectedServiceData.service.path,
        type: 'directory',
        children: selectedServiceData.metadata.autogeneratedFiles.map(f => ({
          name: f.name,
          path: f.path,
          type: 'file',
          fileType: f.type,
          size: f.size,
          lastModified: f.lastModified,
        })),
      }];
    }
    return services.map(s => ({
      name: s.name,
      path: s.path,
      type: 'directory',
      children: [],
    }));
  }, [selectedServiceData, services]);

  // Responsive layout
  const showSidebar = terminalWidth > 100;
  const compactTabBar = terminalWidth < 100;

  return (
    <Box flexDirection="column" height={stdout.rows || 24}>
      {/* Header */}
      <Box backgroundColor="blue" paddingX={1} paddingY={0} height={1}>
        <Text bold color="white"> TDK Interactive UI </Text>
        <Text color="white" dimColor> | {projectRoot}</Text>
      </Box>

      {/* Search indicator */}
      {isSearching && (
        <Box paddingX={1} height={1}>
          <Text color="yellow">Search: {searchQuery}_</Text>
        </Box>
      )}

      {/* Message area */}
      {!isSearching && message && (
        <Box paddingX={1} height={1}>
          <Text color="green">✓ {message}</Text>
        </Box>
      )}

      {/* Help Panel */}
      {showHelp && (
        <Box paddingX={1} flexGrow={1}>
          <HelpPanel onClose={() => setShowHelp(false)} />
        </Box>
      )}

      {/* File Preview */}
      {filePreview && (
        <Box 
          borderStyle="double" 
          borderColor="cyan"
          paddingX={2}
          paddingY={1}
          flexDirection="column"
          flexGrow={1}
          width={terminalWidth - 4}
        >
          <Text bold color="cyan">File Preview</Text>
          <Box marginY={1}>
            <Text color="gray" wrap="wrap">{filePreview.slice(0, 2000)}...</Text>
          </Box>
          <Text color="gray" dimColor>Press [Esc] to close</Text>
        </Box>
      )}

      {/* Main Content (hidden when help or preview is shown) */}
      {!showHelp && !filePreview && (
        <>
          {/* Tab Bar */}
          <Box marginTop={1} paddingX={1}>
            <TabBar 
              activeTab={activeTab} 
              onTabChange={setActiveTab}
              compact={compactTabBar}
            />
          </Box>

          {/* Content Area */}
          <Box flexDirection="row" paddingX={1} flexGrow={1}>
            {/* Left: Main Content */}
            <Box flexDirection="column" flexGrow={1} width={showSidebar ? terminalWidth - 50 : terminalWidth - 4}>
              
              {/* Overview Tab */}
              {activeTab === 'overview' && (
                <>
                  <Text bold underline>📦 Stacks</Text>
                  <Box marginTop={1} flexGrow={1}>
                    <SelectInput 
                      items={items} 
                      onSelect={handleSelect}
                      initialIndex={highlightedIndex}
                      indicatorComponent={({ isSelected }) => (
                        <Text color={isSelected ? 'cyan' : undefined}>{isSelected ? '▸ ' : '  '}</Text>
                      )}
                      itemComponent={({ isSelected, label }) => (
                        <Text color={isSelected ? 'cyan' : 'white'} bold={isSelected}>
                          {label}
                        </Text>
                      )}
                    />
                  </Box>
                </>
              )}

              {/* Resources Tab */}
              {activeTab === 'resources' && (
                <>
                  <Text bold underline>🔧 Resources</Text>
                  {selectedStackData ? (
                    <>
                      <Text color="gray">Stack: {selectedStackData.stack.name}</Text>
                      <Box marginTop={1}>
                        <ResourceTable 
                          services={selectedStackData.metadata.services}
                          maxWidth={terminalWidth - (showSidebar ? 55 : 10)}
                        />
                      </Box>
                    </>
                  ) : (
                    <>
                      <Text color="gray">Select a stack to view resources</Text>
                      <Box marginTop={1}>
                        <SelectInput 
                          items={items} 
                          onSelect={handleSelect}
                          initialIndex={highlightedIndex}
                          indicatorComponent={({ isSelected }) => (
                            <Text color={isSelected ? 'cyan' : undefined}>{isSelected ? '▸ ' : '  '}</Text>
                          )}
                          itemComponent={({ isSelected, label }) => (
                            <Text color={isSelected ? 'cyan' : 'white'} bold={isSelected}>
                              {label}
                            </Text>
                          )}
                        />
                      </Box>
                    </>
                  )}
                </>
              )}

              {/* Events Tab */}
              {activeTab === 'events' && (
                <>
                  <Text bold underline>📅 Events</Text>
                  <Box marginTop={1}>
                    <Text color="gray">Event timeline coming soon...</Text>
                    <Text color="gray" dimColor>
                      This tab will show service lifecycle events,
                      deployments, and health status changes.
                    </Text>
                  </Box>
                </>
              )}

              {/* Files Tab */}
              {activeTab === 'files' && (
                <>
                  <Text bold underline>📁 Autogenerated Files</Text>
                  {selectedServiceData ? (
                    <>
                      <Text color="gray">Service: {selectedServiceData.service.name}</Text>
                      <Box marginTop={1}>
                        <FileTree 
                          nodes={fileTreeNodes}
                          selectedPath={selectedFile || undefined}
                        />
                      </Box>
                    </>
                  ) : (
                    <>
                      <Text color="gray">Select a service to view autogenerated files</Text>
                      <Box marginTop={1}>
                        <SelectInput 
                          items={items} 
                          onSelect={handleSelect}
                          initialIndex={highlightedIndex}
                          indicatorComponent={({ isSelected }) => (
                            <Text color={isSelected ? 'cyan' : undefined}>{isSelected ? '▸ ' : '  '}</Text>
                          )}
                          itemComponent={({ isSelected, label }) => (
                            <Text color={isSelected ? 'cyan' : 'white'} bold={isSelected}>
                              {label}
                            </Text>
                          )}
                        />
                      </Box>
                    </>
                  )}
                </>
              )}

              {/* Config Tab */}
              {activeTab === 'config' && (
                <>
                  <Text bold underline>⚙️ Configuration</Text>
                  {selectedServiceData ? (
                    <Box marginTop={1} flexDirection="column">
                      <Text color="cyan">{selectedServiceData.service.configPath}</Text>
                      <Box marginTop={1} borderStyle="single" borderColor="gray" paddingX={1}>
                        <Text color="gray" wrap="wrap">
                          {JSON.stringify(selectedServiceData.service.config, null, 2).slice(0, 1000)}
                        </Text>
                      </Box>
                    </Box>
                  ) : (
                    <>
                      <Text color="gray">Select a service to view configuration</Text>
                      <Box marginTop={1}>
                        <SelectInput 
                          items={items} 
                          onSelect={handleSelect}
                          initialIndex={highlightedIndex}
                          indicatorComponent={({ isSelected }) => (
                            <Text color={isSelected ? 'cyan' : undefined}>{isSelected ? '▸ ' : '  '}</Text>
                          )}
                          itemComponent={({ isSelected, label }) => (
                            <Text color={isSelected ? 'cyan' : 'white'} bold={isSelected}>
                              {label}
                            </Text>
                          )}
                        />
                      </Box>
                    </>
                  )}
                </>
              )}
            </Box>

            {/* Right: Detail Panel (only on wide terminals) */}
            {showSidebar && (
              <Box marginLeft={2}>
                <DetailPanel 
                  stack={selectedStackData?.stack || null}
                  service={selectedServiceData?.service || null}
                  stackMetadata={selectedStackData?.metadata || null}
                  visible={!!selectedStack || !!selectedService}
                />
              </Box>
            )}
          </Box>

      {/* Status Bar */}
      <Box 
        borderStyle="single" 
        borderColor="gray" 
        paddingX={1}
        height={3}
        flexDirection="column"
        marginTop={1}
      >
        <Box justifyContent="space-between">
          <Text color="cyan" bold>Tab: {activeTab}</Text>
          <Text color="green">● {services.filter(s => s.stack).length} in stack</Text>
          <Text color="yellow">○ {services.filter(s => !s.stack).length} no stack</Text>
          <Text color={showAllServices ? 'magenta' : 'blue'}>
            {showAllServices ? '[a] All services' : '[a] Pre-alpha only'}
          </Text>
        </Box>
        <Box justifyContent="space-between">
          <Text color="gray">Stacks: {stacks.length}</Text>
          <Text color="gray">Services: {services.length}</Text>
          <Text color="gray">🖱️Mouse {mouseEnabled ? 'ON' : 'OFF'} | [?] Help | [q] Quit</Text>
        </Box>
      </Box>
        </>
      )}
    </Box>
  );
};

export const uiCommand = new Command('ui')
  .description('Interactive TUI for managing stacks and services (AWS CDK-style)')
  .alias('interactive')
  .option('-v, --verbose', 'Enable verbose output', false)
  .action(async () => {
    try {
      // Check tilt is available
      const tiltAvailable = await isTiltAvailable();
      if (!tiltAvailable) {
        console.error('Error: tilt CLI not found. Make sure Tilt is installed.');
        process.exit(1);
      }

      const projectRoot = findProjectRoot();
      if (!projectRoot) {
        console.error('Error: Could not find project root (no Tiltfile found).');
        process.exit(1);
      }

      // Render the Ink app
      render(<TUIApp />);

    } catch (err) {
      console.error(`Error: ${err}`);
      process.exit(1);
    }
  });
