# =============================================================================
# 📋 TILT SDK - MANIFEST CONSTANTS (DEPRECATED)
# =============================================================================
# Path: .tilt/topologies/tilt/discovery/manifest/constants.star
# Purpose: DEPRECATED - Re-export from new location for backward compatibility
# 
# ⚠️  WARNING: This file is deprecated and will be removed in Phase 5
#    Use: load("../../manifest/__init__.star", "Manifest")
#    Instead of: load("./manifest/constants.star", "...")
# =============================================================================

# Re-export all constants from new location
# === INLINED CONSTANTS for pure extension loading ===
VALID_DOMAINS = "accounting", "appointment", "appointment-planner", "billing", "gdpr", "identity", "inventory", "mdblaster", "payment", "platform", "reporting", "salon", "staff", "treatment", "website"
VALID_FEATURES = "nats", "prisma", "redis", "infisical", "vitest", "traefik", "websocket", "graphql", "grpc", "vite-node", "maintenance"
PORT_RANGES = {"frontend": {"min": 3000, "max": 5999}, "backend": {"min": 4000, "max": 5999}, "worker": {"min": 6000, "max": 6999}, "migrator": {"min": 7000, "max": 7999}, "sdk": {"min": 3000, "max": 9999}, "library": {"min": 3000, "max": 9999}}
DEFAULTS = {}

# === END INLINED CONSTANTS ===


load("../../../tilt/manifest/constants.star",
    "MANIFEST_FILENAME",
    "MANIFEST_PATTERN",
    "PACKAGE_CONFIG_FILENAMES",
    "GENERATED_CONFIG_FILENAMES",
    "AUTOGENERATED_CONFIG_PATHS",
    "MANIFEST_DEFAULTS",
    "VALID_APP_TYPES",
    "DEFAULT_SYNCS",
    "RUNTIME_CONFIGS",
    "TRAEFIK_DEFAULTS",
    "SERVICE_NAME_PATTERNS",
    "VALIDATION_THRESHOLDS",
    "ManifestConstants",
)


# Re-export for backward compatibility
# All exports are identical to the new location for seamless migration

VALIDATION = {}
