# =============================================================================
# 🎭 TILT SDK - PLAYWRIGHT CONFIG GENERATORS
# =============================================================================
# Path: .tilt/providers/typescript/playwright_config.star
# Purpose: Generate playwright.config.autogenerated.ts for frontend and backend services
# =============================================================================
# Generates service-specific Playwright configurations with different
# settings for:
# - Frontend: UI testing with browser rendering, multiple browsers, visual testing
# - Backend: API testing, REST endpoints, minimal configuration
# =============================================================================


# === INLINED CONSTANTS for pure extension loading ===
OUTPUT = struct(AUTOGENERATED_FOLDER = ".autogenerated")
# === END INLINED CONSTANTS ===

# Load project name for dynamic localhost domain
# Use TDK_PROJECT_ROOT env var set by Tilt, fallback to current directory
def _load_project_localhost():
    project_root = os.environ.get('TDK_PROJECT_ROOT', '')
    project_json_path = '.tdk/project.json'
    if project_root:
        project_json_path = project_root + '/' + project_json_path
    
    if os.path.exists(project_json_path):
        _project_json = read_json(project_json_path)
        return _project_json.get('project', {}).get('name', 'tdk-project') + ".localhost"
    return "tdk-project.localhost"

_PROJECT_LOCALHOST = _load_project_localhost()


load('../../../../topologies/tilt/common/utils.star', 'Utils')
load('../../../../topologies/tilt/manifest/constants.star', 'GENERATED_CONFIG_FILENAMES')


# Load discovery configuration for timeouts
_discovery_config = {}  # get_discovery_config() inlined for pure extension loading


def _get_frontend_config():
    """Get Playwright config for frontend (UI testing)."""
    return """import path from 'node:path';
import {{ fileURLToPath }} from 'node:url';
import {{ defineConfig, devices }} from '@playwright/test';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export default defineConfig({{
  expect: {{
    timeout: {expect_timeout},
  }},
  forbidOnly: !!process.env.CI,
  fullyParallel: false,
  maxFailures: process.env.CI ? undefined : 1,

  outputDir: path.join(__dirname, 'test-results/artifacts'),

  projects: [
    {{
      name: 'chromium',
      use: {{
        ...devices['Desktop Chrome'],
        headless: true,
        viewport: {{ height: 720, width: 1280 }},
      }},
    }},
    {{
      name: 'firefox',
      use: {{
        ...devices['Desktop Firefox'],
        headless: true,
        viewport: {{ height: 720, width: 1280 }},
      }},
    }},
  ],

  reporter: [
    ['list'],
    ['json', {{ outputFile: 'test-results/test-results.json' }}],
    [
      'html',
      {{
        open: 'never',
        outputFolder: 'test-results/html-report',
      }},
    ],
    ['junit', {{ outputFile: 'test-results/junit-report.xml' }}],
    ['blob', {{ outputFile: 'test-results/test-blob-report.zip' }}],
  ],

  retries: process.env.CI ? 2 : 0,
  testDir: './tests/e2e',
  timeout: 60 * 1000,

  use: {{
    actionTimeout: 20000,
    baseURL: process.env.BASE_URL || 'http://localhost:5173',
    trace: 'on-first-retry',
    video: process.env.CI ? 'retain-on-failure' : 'off',
  }},

  webServer: process.env.CI
    ? undefined
    : {{
        command: 'bun run dev',
        port: 5173,
        reuseExistingServer: true,
        timeout: 120 * 1000,
      }},

  workers: process.env.CI ? 1 : undefined,
}});
"""


def _get_backend_config():
    """Get Playwright config for backend (API testing)."""
    return """import {{ defineConfig }} from '@playwright/test';

export default defineConfig({{
  expect: {{
    timeout: {expect_timeout},
  }},

  forbidOnly: !!process.env.CI,
  fullyParallel: false,

  reporter: [
    ['list'],
    ['json', {{ outputFile: 'test-results/test-results.json' }}],
    [
      'html',
      {{
        open: 'never',
        outputFolder: 'test-results/html-report',
      }},
    ],
    ['junit', {{ outputFile: 'test-results/junit-report.xml' }}],
  ],

  retries: process.env.CI ? 2 : 0,
  testDir: './test',
  timeout: {timeout},

  use: {{
    baseURL: process.env.BASE_URL || 'http://{localhost}/api/v1/identity',
    extraHTTPHeaders: {{
      'Content-Type': 'application/json',
    }},
    trace: 'on-first-retry',
  }},

  workers: 1,
}});
""".format(
    expect_timeout=5000,  # 5 seconds for expect timeout
    timeout=_discovery_config.get("playwright_timeout_ms", 30000),  # Default 30s timeout
    localhost=_PROJECT_LOCALHOST,
)


def generate_playwright_config(resource_path, service_type='backend', write_file_if_changed=None):
    """
    Generate playwright.config.autogenerated.ts for a service.
    
    Args:
        resource_path: Full path to service directory (e.g., 'services/product/order/order-management-frontend')
        service_type: 'frontend' or 'backend' (default: 'backend')
        write_file_if_changed: Optional file writer function
    
    Returns:
        Generated playwright.config.autogenerated.ts content
    """
    # Extract service name from path for header
    service_name = resource_path.split('/')[-1]
    
    # Generate header using shared utility
    header = Utils.get_template_header(
        GENERATED_CONFIG_FILENAMES['playwright'],
        'TypeScript.generate_playwright_config()',
        service_name,
        service_type.upper()
    )

    # Select appropriate config template
    if service_type == 'frontend':
        config_body = _get_frontend_config()
    else:  # backend or default
        config_body = _get_backend_config()

    # Add header to config body
    content = header + config_body
    
    if write_file_if_changed:
        write_file_if_changed(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['playwright'], content)

    return content
