# =============================================================================
# 🧱 TILT SDK - TYPESCRIPT BUILDERS
# =============================================================================
# Path: .tilt/provisioner/orchestrator/builders/typescript.star
# Purpose: TypeScript build helpers for orchestrator
# =============================================================================


# === INLINED CONSTANTS for pure extension loading ===
OUTPUT = struct(AUTOGENERATED_FOLDER = ".autogenerated")
DEFAULTS = {}

# === END INLINED CONSTANTS ===


load('../../../common/utils.star', 'Utils')
# Import filewatch ignore patterns from master config (replaces hardcoded values)


def _with_service_prefix(pattern, service_path):
    """Prefix dockerignore pattern so it applies to the service subtree in root context."""
    normalized = pattern
    if normalized.startswith('/'):
        normalized = normalized[1:]

    # Patterns in autogenerated dockerignore are service-relative.
    # docker_build context is '.', so scope them under service_path.
    return service_path + '/' + normalized


def get_filewatch_ignore_patterns(service_path):
    """Return filewatch ignore patterns to prevent fsnotify buffer overflow."""
    return [
        service_path + "/node_modules",
        service_path + "/dist",
        service_path + "/build",
        service_path + "/.git",
        service_path + "/.prisma",
        service_path + "/.turbo",
        service_path + "/coverage",
        service_path + "/tmp",
        service_path + "/temp",
    ]

def _load_autogenerated_dockerignore_patterns(dockerfile_path, service_path):
    """
    Read Dockerfile-specific autogenerated dockerignore and convert to Tilt ignore rules.
    Note: Tilt ignore does not support negate patterns ('!'), so those are skipped.
    """
    dockerignore_path = dockerfile_path + '.dockerignore'
    content = read_file(dockerignore_path, default='')

    if not content:
        return []

    ignore_patterns = []
    for raw_line in str(content).split('\n'):
        line = raw_line.strip()
        if not line or line.startswith('#') or line.startswith('!'):
            continue
        ignore_patterns.append(_with_service_prefix(line, service_path))

    return ignore_patterns

def _get_service_only_paths(service_path):
    """
    Generate minimal file paths for docker_build 'only' parameter.
    This dramatically reduces build context from 7.4GB to just the necessary files.
    
    Args:
        service_path: Path to service (e.g., 'services/product/{domain}/{service-name}')
    
    Returns:
        List of paths to include in build context
    """
    only_paths = [
        # Root level dependencies
        'bun.lock',
        'bun.lockb',
        'package.json',
        
        # Service-specific files
        service_path,
        
        # Shared runtime scripts copied in generated Dockerfiles.
        'shared-platform-engineering/docker-templates',

        # Common DDD layers used by backend Dockerfiles.
        'shared-ddd-layers/domain',
        'shared-ddd-layers/infrastructure',
    ]

    # Include only internal libraries referenced by this service package.json.
    # This prevents unrelated library changes from triggering global rebuilds.
    deps_map = Utils.build_deps_mapping(service_path)
    for dep_path in deps_map.values():
        if dep_path not in only_paths:
            only_paths.append(dep_path)

    return only_paths

def _build_typescript_service(name, context, dockerfile, live_update_rules, deps, env=None):
    """Build a TypeScript service with Docker.
    
    Args:
        name: Resource name
        context: Docker build context
        dockerfile: Path to Dockerfile
        live_update_rules: Live update configuration
        deps: Resource dependencies
        env: Dict of environment variables to pass to container (optional)
    """
    # Extract service path from dockerfile path (e.g., 'services/product/{domain}/{service-name}')
    # The dockerfile parameter looks like: 'services/product/{domain}/{service-name}/autogenerated/Dockerfile.autogenerated'
    service_path = '/'.join(dockerfile.split('/')[:-1])
    
    # Handle both 'autogenerated' (without dot) and '.autogenerated' (with dot)
    # Some services use 'autogenerated', others use '.autogenerated' folder
    autogenerated_folders = ['autogenerated', '.autogenerated']
    for folder in autogenerated_folders:
        suffix = '/' + folder
        if service_path.endswith(suffix):
            service_path = service_path[:-len(suffix)]
            break
    
    # Also check OUTPUT.AUTOGENERATED_FOLDER for consistency
    if service_path.endswith('/' + OUTPUT.AUTOGENERATED_FOLDER):
        service_path = service_path[:-(len('/' + OUTPUT.AUTOGENERATED_FOLDER))]

    ignore_patterns = _load_autogenerated_dockerignore_patterns(dockerfile, service_path)
    
    # CRITICAL FIX: Add filewatch ignore patterns from master config
    # These prevent fsnotify buffer overflow by excluding high-churn directories
    # Previously hardcoded; now imported from TILT_SERVICE_DEFAULTS.star
    additional_ignores = get_filewatch_ignore_patterns(service_path)
    
    # Merge patterns, avoiding duplicates
    for pattern in additional_ignores:
        if pattern not in ignore_patterns:
            ignore_patterns.append(pattern)
    
    only_paths = _get_service_only_paths(service_path)
    print("DEBUG: Building " + name + " with service_path: " + service_path)
    print("DEBUG: only_paths: " + str(only_paths))
    
    # Build context must be the project root (.) so that COPY commands can reference
    # shared-platform-engineering/, shared-ddd-layers/, and services/ directories
    # BUT we use 'only' to dramatically reduce the context size (from 7.4GB to ~100MB)
    # Build kwargs dict to conditionally add env if provided
    build_kwargs = {
        'dockerfile': dockerfile,
        'target': 'production',
        'live_update': live_update_rules,
        'only': _get_service_only_paths(service_path),
        'ignore': ignore_patterns,
        'network': 'host',
    }
    
    # Add environment variables if provided
    if env:
        build_kwargs['env'] = env
    
    docker_build(
        name,
        '.',
        **build_kwargs
    )


TypescriptBuilders = struct(
    build_typescript_service = _build_typescript_service,
    load_dockerignore_patterns = _load_autogenerated_dockerignore_patterns,
)

DEBUG = {}
