/**
 * Tooltip Component - Neon Edition
 * 
 * Contextual help that appears on hover/focus
 */

import React from 'react';
import { Box, Text } from 'ink';

interface TooltipProps {
  content: string;
  shortcut?: string;
  visible: boolean;
  maxWidth?: number;
}

// Tooltip component - currently unused internally
const Tooltip: React.FC<TooltipProps> = ({ 
  content, 
  shortcut, 
  visible,
  maxWidth = 40 
}) => {
  if (!visible) return null;

  // Wrap text to maxWidth
  const words = content.split(' ');
  const lines: string[] = [];
  let currentLine = '';
  
  for (const word of words) {
    if ((currentLine + word).length > maxWidth - 2) {
      lines.push(currentLine.trim());
      currentLine = word + ' ';
    } else {
      currentLine += word + ' ';
    }
  }
  if (currentLine) {
    lines.push(currentLine.trim());
  }

  return (
    <Box 
      flexDirection="column"
      borderStyle="single"
      borderColor="yellow"
      paddingX={1}
      paddingY={1}
      backgroundColor="black"
      position="absolute"
    >
      {lines.map((line, i) => (
        <Text key={i} color="yellow">{line}</Text>
      ))}
      {shortcut && (
        <Box marginTop={1}>
          <Text color="gray">Press </Text>
          <Text color="cyan" bold>{shortcut}</Text>
          <Text color="gray"> to use</Text>
        </Box>
      )}
    </Box>
  );
};

// Tooltip definitions for different UI elements
export const TOOLTIPS = {
  overviewTab: 'View all stacks and their resources',
  resourcesTab: 'Detailed resource list with metadata',
  eventsTab: 'Service lifecycle events timeline',
  filesTab: 'Browse autogenerated configuration files',
  configTab: 'View and edit service configurations',
  search: 'Filter services by name, stack, or type',
  refresh: 'Reload data from Tilt API',
  help: 'Show keyboard shortcuts and help',
  quit: 'Exit the TUI',
};
