appName: payment-processing-backend
appType: backend
stack: billing
port: 4013
apiPath: /api/payment-processing
features:
  - nats
  - prisma
infisicalSecretPath: /services/billing
internalDependencies:
  - payment-management-backend
  - identity-management-backend
replicas: 1
runtime: bun
