appName: appointment-planner-builder-frontend
appType: frontend
stack: appointment-planner
port: 3001
backendName: appointment-planner-builder-backend
basePath: /appointment-planner-builder
enabled: True
runtime: bun
