import type { ResourceType } from '../types/index.js';

/**
 * Master configuration files generated by TDK
 * Used across project.ts, config.ts, template-engine.ts, and tests
 */
export const MASTER_CONFIG_FILES = [
  'TILT_TECH_STACK.star',
  'TILT_RESOURCE_DEFAULTS.star',
  'spec.master',
] as const;

/**
 * Valid resource types for the resource command
 * Aligned with ResourceType type from types/index.ts
 * Derived from ResourceType to ensure type safety and prevent drift
 */
export const VALID_RESOURCE_TYPES: ResourceType[] = [
  'backend',
  'frontend',
  'library',
  'sdk',
  'worker',
  'migrator',
] as const;

/**
 * Optional infrastructure services
 * Used in config.ts enable-infra/disable-infra subcommands
 */
export const OPTIONAL_INFRA_SERVICES = [
  'monitoring',
  'elk',
  'debezium',
  'golden_image',
] as const;

/**
 * Port range configuration by resource type
 * Single source of truth for all port assignments
 * Used by: resource.ts, platform-standards.ts, template-engine.ts
 */
export const PORT_RANGES = {
  frontend: { base: 3000, min: 3000, max: 3999, range: "3000-3999" as const },
  backend: { base: 4000, min: 4000, max: 4999, range: "4000-4999" as const },
  worker: { base: 6000, min: 6000, max: 6999, range: "6000-6999" as const },
  health: { base: 5000, min: 5000, max: 5999, range: "5000-5999" as const },
  migrator: { base: 7000, min: 7000, max: 7999, range: "7000-7999" as const },
} as const;

/**
 * Standard service ports (non-range)
 */
export const STANDARD_PORTS = {
  tiltUi: 10350,
  traefik: 8080,
} as const;

/**
 * Directories to skip during filesystem scanning
 * Extracted from services.ts shouldSkipDirectory()
 */
export const SKIP_DIRECTORIES = [
  'node_modules',
  '.git',
  '.tilt',
  '.tilt-engine',
  'dist',
  'build',
  '.prisma',
  '.turbo',
  'coverage',
  'tmp',
  'temp',
  '__tests__',
  'test',
  'tests',
  '.github',
  '.vscode',
  'docs',
] as const;

/**
 * File patterns considered autogenerated
 * Used in discoverAutogeneratedFiles()
 */
export const AUTOGENERATED_FILE_PATTERNS = [
  'Dockerfile',
  'docker-compose.yml',
  'docker-compose.yaml',
  'Tiltfile',
  'vite.config.ts',
  'tsconfig.json',
  'tsconfig.build.json',
] as const;

/**
 * Emoji mappings for stack names
 * Used by networks command for visual stack identification
 * Internal use only - not exported, use getStackEmoji() instead
 */
const STACK_EMOJIS: Record<string, string> = {
  'identity': '🔐',
  'order': '📅',
  'payment': '💳',
  'staff': '👥',
  'inventory': '📦',
  'user': '👤',
  'website': '🌐',
  'treatment': '💆',
  'gdpr': '🔒',
  'orchestrator': '⚙️',
} as const;

/**
 * Get emoji for a stack name based on partial matching
 * @param stackName - The stack name to match
 * @returns Matching emoji or default 📦
 */
export function getStackEmoji(stackName: string): string {
  const lowerName = stackName.toLowerCase();
  for (const [key, emoji] of Object.entries(STACK_EMOJIS)) {
    if (lowerName.includes(key)) {
      return emoji;
    }
  }
  return '📦';
}
