import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { resolve, join, dirname } from 'node:path';
import type {
  DiscoveredResource,
  ResourceConfig,
  DiscoveredStack,
  ResourceMetadata,
  StackMetadata,
  AutogeneratedFile,
  FileType,
  ResourceType,
} from '../types/index.js';
import { SKIP_DIRECTORIES, AUTOGENERATED_FILE_PATTERNS } from './constants.js';
import { sanitizeForShell, includes } from './validation.js';
import { findProjectRoot } from './paths.js';
import { getErrorMessage } from './errors.js';

/**
 * Type guard to check if an error is a NodeJS.ErrnoException
 * Safely checks for the `code` property that exists on Node.js system errors
 */
function isNodeError(err: unknown): err is NodeJS.ErrnoException {
  return err instanceof Error && 'code' in err;
}

const RESOURCE_JSON_FILENAME = 'service.json';

function findServiceJsonFiles(dir: string, maxDepth: number = 5, currentDepth: number = 0): string[] {
  const results: string[] = [];

  if (currentDepth > maxDepth) {
    return results;
  }

  try {
    const entries = readdirSync(dir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = join(dir, entry.name);

      if (entry.isDirectory()) {
        if (shouldSkipDirectory(entry.name)) continue;
        results.push(...findServiceJsonFiles(fullPath, maxDepth, currentDepth + 1));
      } else if (entry.isFile() && entry.name === RESOURCE_JSON_FILENAME) {
        results.push(fullPath);
      }
    }
  } catch (err: unknown) {
    const errorCode = isNodeError(err) ? err.code : undefined;
    if (errorCode !== 'ENOENT') {
      console.warn(`Warning: Could not read directory ${dir}: ${getErrorMessage(err)}`);
    }
  }

  return results;
}

function shouldSkipDirectory(name: string): boolean {
  return includes(SKIP_DIRECTORIES, name) || name.startsWith('.');
}

function isValidResourceConfig(value: unknown): value is ResourceConfig {
  if (!value || typeof value !== 'object') return false;
  const config = value as Record<string, unknown>;
  return typeof config.appName === 'string' && typeof config.runtime === 'string';
}

function parseResource(serviceJsonPath: string): DiscoveredResource {
  const content = readFileSync(serviceJsonPath, 'utf-8');
  const parsed: unknown = JSON.parse(content);

  if (!isValidResourceConfig(parsed)) {
    throw new Error(`Invalid service.json at ${serviceJsonPath}: missing required fields (appName, runtime)`);
  }

  const config: ResourceConfig = parsed;
  const resourceDir = dirname(serviceJsonPath);

  return {
    name: config.appName,
    path: resourceDir,
    configPath: serviceJsonPath,
    config,
    stack: config.stack,
  };
}

export function discoverResources(): DiscoveredResource[] {
  const projectRoot = findProjectRoot();

  if (!projectRoot) {
    throw new Error('Could not find project root (no Tiltfile found). Make sure you\'re in a root project.');
  }

  const serviceJsonPaths = findServiceJsonFiles(projectRoot);
  const resources: DiscoveredResource[] = [];

  for (const path of serviceJsonPaths) {
    try {
      resources.push(parseResource(path));
    } catch (err: unknown) {
      console.warn(`Warning: Failed to parse service.json at ${path}: ${getErrorMessage(err)}`);
    }
  }

  return resources;
}

export function getAllStacks(resources?: DiscoveredResource[]): string[] {
  const resourcesToScan = resources || discoverResources();
  const stacks = new Set<string>();

  for (const resource of resourcesToScan) {
    if (resource.stack) {
      stacks.add(resource.stack);
    }
  }

  return Array.from(stacks).sort();
}

export function discoverStacks(): DiscoveredStack[] {
  const resources = discoverResources();
  const stackMap = new Map<string, DiscoveredResource[]>();

  for (const resource of resources) {
    if (resource.stack) {
      if (!stackMap.has(resource.stack)) {
        stackMap.set(resource.stack, []);
      }
      stackMap.get(resource.stack)!.push(resource);
    }
  }

  const stacks: DiscoveredStack[] = [];
  for (const [name, stackResources] of stackMap) {
    stacks.push({
      name,
      description: `${stackResources.length} resource${stackResources.length === 1 ? '' : 's'}`,
      resources: stackResources,
      resourceCount: stackResources.length,
    });
  }

  return stacks.sort((a, b) => a.name.localeCompare(b.name));
}

export function getResourcesForStack(stackName: string): DiscoveredResource[] {
  const allResources = discoverResources();
  return allResources.filter(r => r.stack === stackName);
}

export function stackExists(stackName: string): boolean {
  const resources = getResourcesForStack(stackName);
  return resources.length > 0;
}

interface MetadataCache {
  resources: Map<string, ResourceMetadata>;
  stacks: Map<string, StackMetadata>;
  lastUpdated: number;
}

const CACHE_TTL = 5000;

const metadataCache: MetadataCache = {
  resources: new Map(),
  stacks: new Map(),
  lastUpdated: 0,
};

export function clearMetadataCache(): void {
  metadataCache.resources.clear();
  metadataCache.stacks.clear();
  metadataCache.lastUpdated = 0;
}

function isCacheValid(): boolean {
  return Date.now() - metadataCache.lastUpdated < CACHE_TTL;
}

function detectFileType(filename: string, content?: string): FileType {
  if (filename === 'Dockerfile' || filename.startsWith('docker-compose')) {
    return 'docker';
  }
  if (filename === 'Tiltfile' || filename.endsWith('.star')) {
    return 'tilt';
  }
  if (filename === 'vite.config.ts' || filename === 'tsconfig.json' || filename === 'package.json') {
    return 'config';
  }
  if (filename === 'schema.prisma' || filename.includes('migration')) {
    return 'prisma';
  }
  if (content) {
    const firstLines = content.split('\n').slice(0, 10).join('\n');
    if (firstLines.includes('GENERATED BY TDK') || firstLines.includes('AUTOGENERATED')) {
      return 'generated';
    }
  }
  return 'unknown';
}

export function getResourceMetadata(resource: DiscoveredResource): ResourceMetadata {
  const cacheKey = resource.configPath;
  
  if (isCacheValid() && metadataCache.resources.has(cacheKey)) {
    return metadataCache.resources.get(cacheKey)!;
  }

  const resourceDir = resource.path;
  
  let createdAt = new Date().toISOString();
  let lastModified = createdAt;
  try {
    const stats = statSync(resource.configPath);
    createdAt = stats.mtime.toISOString();
    lastModified = stats.mtime.toISOString();
  } catch (err: unknown) {
    console.warn(`Warning: Could not read timestamps for ${resource.configPath}: ${getErrorMessage(err)}`);
  }

  const autogeneratedFiles = discoverAutogeneratedFiles(resourceDir);
  const hasDockerfile = existsSync(join(resourceDir, 'Dockerfile'));
  const hasTiltfile = existsSync(join(resourceDir, 'Tiltfile'));
  const hasDockerCompose = existsSync(join(resourceDir, 'docker-compose.yml')) || 
                          existsSync(join(resourceDir, 'docker-compose.yaml'));

  const configType = resource.config?.appType;
  let type: ResourceType = configType || 'backend';
  if (!configType) {
    if (resource.name.includes('frontend')) {
      type = 'frontend';
    } else if (resource.name.includes('sdk') || resource.name.includes('lib') || resource.name.includes('infra')) {
      type = 'library';
    }
  }

  const metadata: ResourceMetadata = {
    name: resource.name,
    stack: resource.stack,
    type,
    port: resource.config?.port,
    createdAt,
    lastModified,
    dependencies: resource.config?.dependencies || resource.config?.internalDependencies || [],
    hasDockerfile,
    hasTiltfile,
    hasDockerCompose,
    autogeneratedFiles,
    status: 'unknown',
  };

  metadataCache.resources.set(cacheKey, metadata);
  metadataCache.lastUpdated = Date.now();

  return metadata;
}

export function discoverAutogeneratedFiles(resourceDir: string): AutogeneratedFile[] {
  const files: AutogeneratedFile[] = [];

  for (const pattern of AUTOGENERATED_FILE_PATTERNS) {
    const filePath = join(resourceDir, pattern);
    if (existsSync(filePath)) {
      try {
        const stats = statSync(filePath);
        const content = readFileSync(filePath, 'utf-8');

        files.push({
          name: pattern,
          path: filePath,
          type: detectFileType(pattern, content),
          size: stats.size,
          lastModified: stats.mtime.toISOString(),
        });
      } catch (err: unknown) {
        const errorCode = isNodeError(err) ? err.code : undefined;
        if (errorCode !== 'ENOENT' && errorCode !== 'EACCES') {
          console.warn(`Warning: Could not read file ${filePath}: ${getErrorMessage(err)}`);
        }
      }
    }
  }

  const prismaDir = join(resourceDir, 'prisma');
  if (existsSync(prismaDir)) {
    try {
      const entries = readdirSync(prismaDir);
      for (const entry of entries) {
        if (entry === 'schema.prisma' || entry.includes('migration')) {
          const filePath = join(prismaDir, entry);
          const stats = statSync(filePath);
          files.push({
            name: `prisma/${entry}`,
            path: filePath,
            type: 'prisma',
            size: stats.size,
            lastModified: stats.mtime.toISOString(),
          });
        }
      }
    } catch (err: unknown) {
      const errorCode = isNodeError(err) ? err.code : undefined;
      if (errorCode !== 'ENOENT') {
        console.warn(`Warning: Could not read prisma directory ${prismaDir}: ${getErrorMessage(err)}`);
      }
    }
  }

  return files.sort((a, b) => a.name.localeCompare(b.name));
}

export function getStackMetadata(stack: DiscoveredStack): StackMetadata {
  const cacheKey = stack.name;
  
  if (isCacheValid() && metadataCache.stacks.has(cacheKey)) {
    return metadataCache.stacks.get(cacheKey)!;
  }

  const resourcesMetadata = stack.resources.map(r => getResourceMetadata(r));
  const timestamps = resourcesMetadata.map(r => new Date(r.createdAt).getTime());
  const earliestTimestamp = Math.min(...timestamps);
  const latestTimestamp = Math.max(...timestamps);
  const totalResources = resourcesMetadata.length;
  // TODO: Replace with real health check aggregation from Tilt API or service health endpoints
  const readyCount = resourcesMetadata.filter(() => Math.random() > 0.3).length;
  
  let overallStatus: StackMetadata['overallStatus'] = 'unknown';
  if (totalResources > 0) {
    const ratio = readyCount / totalResources;
    if (ratio > 0.9) {
      overallStatus = 'healthy';
    } else if (ratio > 0.5) {
      overallStatus = 'degraded';
    } else {
      overallStatus = 'error';
    }
  }

  const metadata: StackMetadata = {
    name: stack.name,
    resourceCount: resourcesMetadata.length,
    createdAt: new Date(earliestTimestamp).toISOString(),
    lastModified: new Date(latestTimestamp).toISOString(),
    resources: resourcesMetadata,
    overallStatus,
  };

  metadataCache.stacks.set(cacheKey, metadata);
  metadataCache.lastUpdated = Date.now();

  return metadata;
}


