export type {
  DiscoveredResource,
  DiscoveredStack,
  ResourceConfig,
  ResourceMetadata,
  StackMetadata,
  AutogeneratedFile,
  ResourceStatus,
  StackHealthStatus,
  ResourceType,
  FileType,
  TiltRuntimeStatus,
  TiltBuildStatus,
  TiltResourceStatus,
  TiltCommandResult,
  CreatableResourceType,
  JsonValue,
  JsonArray,
  JsonObject,
  ProjectConfig,
  ProjectStackDefinition,
  ProjectOptionalInfra,
  ProjectDiscovery,
  ServiceUrl,
  SelectItem,
  ValidationResult,
  CheckResult,
  TabId,
  Tab,
  TabBarProps,
  FileNode,
  FileTreeProps,
  DetailPanelProps,
  ResourceTableProps,
  ResourceSelectInputProps,
  TooltipProps,
  BaseTooltipProps,
  LoadingScreenProps,
  ErrorScreenProps,
  HelpPanelProps,
  DiscoveryContext,
  StatusValue,
  StatusCategory,
  FileGenerationTask,
  ResourceFileType,
} from './types/index.js';

export {
  CREATABLE_RESOURCE_TYPES,
  isCreatableResourceType,
} from './types/index.js';

export {
  discoverResources,
  discoverStacks,
  getAllStacks,
  getResourcesForStack,
  stackExists,
  clearMetadataCache,
  getResourceMetadata,
  getStackMetadata,
} from './utils/services.js';

// Re-export discovery-context functions for resources-by-stack operations
export {
  createDiscoveryContext,
} from './utils/discovery-context.js';

export {
  findProjectRoot,
} from './utils/paths.js';

export {
  runTilt,
  isTiltAvailable,
  getTiltfilePath,
  buildTiltUpArgs,
  buildTiltDownArgs,
} from './utils/tilt.js';

export {
  findAvailablePort,
} from './utils/port-assignment.js';

export {
  confirmAction,
  confirmOrCancel,
  assertValid,
  handleDryRun,
} from './utils/command-helpers.js';

export {
  Cache,
  createCacheValidator,
} from './utils/cache.js';

export {
  writeFilesWithProgress,
} from './utils/file-helpers.js';

export {
  checkPortStatus,
} from './utils/port-assignment.js';


