/**
 * TDK (Tilt Development Kit)
 *
 * A CLI tool for managing resources and stacks in Tilt-based microservice projects.
 *
 * Stacks are discovered dynamically from service.json files - no stack.master needed.
 *
 * @packageDocumentation
 */

// Type exports - explicitly listed for clean public API
export type {
  // Core resource types
  DiscoveredResource,
  DiscoveredStack,
  ResourceConfig,
  ResourceMetadata,
  StackMetadata,
  AutogeneratedFile,
  // Status types
  ResourceStatus,
  StackHealthStatus,
  ResourceType,
  FileType,
  TiltRuntimeStatus,
  TiltBuildStatus,
  TiltResourceStatus,
  TiltCommandResult,
  // CLI types
  CLIOptions,
} from './types/index.js';

// Service utilities
export {
  // Resource discovery
  discoverResources,
  discoverStacks,
  getAllStacks,
  getResourcesForStack,
  stackExists,
  // Project utilities
  findProjectRoot,
  clearMetadataCache,
  getResourceMetadata,
  discoverAutogeneratedFiles,
  getStackMetadata,
  getTiltResourceStatus,
} from './utils/services.js';

// Tilt command utilities
export {
  isPortAvailable,
  findAvailablePort,
  runTilt,
  isTiltAvailable,
  getTiltfilePath,
  buildTiltUpArgs,
  buildTiltDownArgs,
} from './utils/tilt.js';
