# =============================================================================
# 🎨 TILT SDK - FRONTEND API CLIENT GENERATORS
# =============================================================================
# Purpose: Generate api-client.ts, env.ts, and index.ts for frontend services
#          These files import from @beauty-crm/platform-api-client package
# =============================================================================

load("../../../../platform/docker/networking/traefik_helpers.star", "get_api_path")
load("../../../../platform/docker/constants.star", "PlatformDockerConstants")
load("./dependencies/resolver.star", "resolve_backend_api_path")

def generate_frontend_api_client(manifest, write_file_fn=None):
    """Generate autogenerated/api-client.ts for a frontend service.
    
    Args:
        manifest: Service manifest with domain field
        write_file_fn: Optional function to write file (for Tilt)
    
    Returns:
        str: Generated file content
    """
    domain = manifest.get("domain", "app")
    
    # Auto-resolve apiPath from backend manifest if backendName is specified
    backend_api_path = resolve_backend_api_path(manifest)
    if backend_api_path:
        api_path = backend_api_path
    else:
        api_path = get_api_path(domain, manifest)
    
    content = '''// 🛑 GENERATED BY TILT SDK - DO NOT EDIT
// Source: .tilt/topologies/tilt/resources/orchestrator/generators/frontend.star
// Purpose: Pre-configured API client for {domain} service

import {{ createApiClient }} from '@beauty-crm/platform-api-client';

/**
 * Pre-configured API client for {domain} service
 * 
 * Usage:
 * ```typescript
 * import {{ apiClient }} from '../autogenerated/api-client';
 * const data = await apiClient.get('/');
 * ```
 */
export const apiClient = createApiClient({{
  baseURL: import.meta.env.VITE_API_URL || 'http://{local_domain}{api_path}',
  withAuth: true,
}});

export default apiClient;
'''.format(
        domain=domain,
        api_path=api_path,
        local_domain=PlatformDockerConstants.LOCAL_DOMAIN,
    )
    
    if write_file_fn:
        service_path = manifest.get('_servicePath', '')
        write_file_fn(service_path + '/autogenerated/api-client.ts', content)
    
    return content


def generate_frontend_env_ts(manifest, write_file_fn=None):
    """Generate autogenerated/env.ts for a frontend service.
    
    Args:
        manifest: Service manifest with domain field
        write_file_fn: Optional function to write file (for Tilt)
    
    Returns:
        str: Generated file content
    """
    domain = manifest.get("domain", "app")
    
    # Auto-resolve apiPath from backend manifest if backendName is specified
    backend_api_path = resolve_backend_api_path(manifest)
    if backend_api_path:
        api_path = backend_api_path
    else:
        api_path = get_api_path(domain, manifest)
    
    content = '''// 🛑 GENERATED BY TILT SDK - DO NOT EDIT
// Source: .tilt/topologies/tilt/resources/orchestrator/generators/frontend.star
// Purpose: Environment constants for {domain} service

/**
 * Base API URL for {domain} service
 * Uses VITE_API_URL env var with fallback to local dev URL
 */
export const API_URL = import.meta.env.VITE_API_URL || 'http://{local_domain}{api_path}';

/**
 * Default export for convenience
 * @deprecated Use named export API_URL instead
 */
export default API_URL;
'''.format(
        domain=domain,
        api_path=api_path,
        local_domain=PlatformDockerConstants.LOCAL_DOMAIN,
    )
    
    if write_file_fn:
        service_path = manifest.get('_servicePath', '')
        write_file_fn(service_path + '/autogenerated/env.ts', content)
    
    return content


def generate_frontend_api_index(manifest, write_file_fn=None):
    """Generate autogenerated/api-index.ts for clean imports.
    
    Args:
        manifest: Service manifest
        write_file_fn: Optional function to write file (for Tilt)
    
    Returns:
        str: Generated file content
    """
    content = '''// 🛑 GENERATED BY TILT SDK - DO NOT EDIT
// Source: .tilt/topologies/tilt/resources/orchestrator/generators/frontend.star
// Purpose: Clean barrel exports for API client

export { apiClient, default } from './api-client';
export { API_URL, default as API_URL_DEFAULT } from './env';
'''
    
    if write_file_fn:
        service_path = manifest.get('_servicePath', '')
        write_file_fn(service_path + '/autogenerated/api-index.ts', content)
    
    return content


def generate_all_frontend_api_files(manifest, write_file_fn=None):
    """Generate all frontend API files for a service.
    
    Args:
        manifest: Service manifest
        write_file_fn: Function to write files
    
    Returns:
        dict: Generated content for each file
    """
    return {
        'api-client.ts': generate_frontend_api_client(manifest, write_file_fn),
        'env.ts': generate_frontend_env_ts(manifest, write_file_fn),
        'api-index.ts': generate_frontend_api_index(manifest, write_file_fn),
    }


# Export struct for easy importing
FrontendGenerators = struct(
    generate_api_client = generate_frontend_api_client,
    generate_env_ts = generate_frontend_env_ts,
    generate_api_index = generate_frontend_api_index,
    generate_all = generate_all_frontend_api_files,
)
